### ISSUE TITLE
soundcloud

### ISSUE THREAD

**Issue by xxcriticxx** [pascalopitz/unoffical-sonos-controller-for-linux#10]
@pascalopitz under popular music trying to add 100 tracks i get errors 

`POST http://192.168.1.116:1400/MediaRenderer/AVTransport/Control 500 (Internal Server Error)`
`POST http://192.168.1.116:1400/MediaRenderer/AVTransport/Control 500 (Internal Server Error)`
`POST http://192.168.1.116:1400/MediaRenderer/AVTransport/Control 500 (Internal Server Error)`
`POST http://192.168.1.116:1400/MediaRenderer/AVTransport/Control 500 (Internal Server Error)`
`GET http://192.168.1.116:1400/getaa?s=1&u=x-sonos-http:track%3a297836706.mp3?sid=160&flags=8224&sn=5 404 (Not Found)`

**Comment by xxcriticxx** [comment]
this worked in ver 0.8

**Comment by pascalopitz** [comment]
Hi there. To be able to have a bit of an idea of what's going on, I'd need
the request and response payload, whether this happened in a music service
context etc etc.

**Comment by xxcriticxx** [comment]
@pascalopitz if i understand correctly i open soundcloud on my iphone add 100 tracks played few songs removed them and try the same with the app and got errors and could not add them

`Failed to load resource: the server responded with a status of 404 (Not Found)`
`Failed to load resource: the server responded with a status of 404 (Not Found)`
`POST http://192.168.1.116:1400/MediaRenderer/AVTransport/Control 500 (Internal Server Error)`

**Comment by pascalopitz** [comment]
do let's ignore the 404s here. for the 500s, can you attach the request and response payload?

**Comment by xxcriticxx** [comment]
@pascalopitz provide info how and i get it to you

**Comment by pascalopitz** [comment]
https://developers.google.com/web/tools/chrome-devtools/network-performance/resource-loading

**Comment by xxcriticxx** [comment]
@pascalopitz let me know if you need anything else

![screenshot from 2016-12-24 09-30-28](https://cloud.githubusercontent.com/assets/15007183/21467456/c0691b60-c9bc-11e6-8488-572fda6aa8ee.png)

**Comment by pascalopitz** [comment]
You'll need to click on the red request in the upper panel, then you'll be able to inspect it and see the XML payload and raw headers, and the according response

**Comment by xxcriticxx** [comment]
@pascalopitz you got all that info in pastebin i left if thats not what you looking for can you draw on my pic what you want me to click on

**Comment by xxcriticxx** [comment]
@pascalopitz do you need any other information from me?

**Comment by pascalopitz** [comment]
Is this still an issue in the latest pre-release alpha6?

**Comment by xxcriticxx** [comment]
alpha5 service works search works its slow but works. need option to add all songs to queue loading one by one is pain in ass.

**Comment by pascalopitz** [comment]
All songs where? in a search? In a playlist?

**Comment by xxcriticxx** [comment]
all songs from search to que. it would be nice to have for all music services It's not a priority right now
