### ISSUE TITLE
Warnings in developer console - can they be ignored?

### ISSUE THREAD

**Issue by My-Random-Thoughts** [pascalopitz/unoffical-sonos-controller-for-linux#101]
@davidpgil mentioned this in issue #14 but I don't think it was answered. (https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/issues/14#issuecomment-657060788)

EDIT: Using v0.2.0 on a old firmware of first gen Play:1

These are shown as soon as the console is opened or a refresh is done

    /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    Please update the following components: VirtualList
    printWarning @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:88
    warn @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:51
    ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11377
    flushRenderPhaseStrictModeWarningsInDEV @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23112
    commitRootImpl @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22396
    unstable_runWithPriority @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:653
    runWithPriority$1 @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11039
    commitRoot @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22381
    finishSyncRender @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21807
    performSyncWorkOnRoot @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21793
    (anonymous) @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11089
    unstable_runWithPriority @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:653
    runWithPriority$1 @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11039
    flushSyncCallbackQueueImpl @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11084
    flushSyncCallbackQueue @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11072
    unbatchedUpdates @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21909
    legacyRenderSubtreeIntoContainer @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24757
    render @ /tmp/.mount_sonos-njYwR3/resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:24840
    (anonymous) @ /tmp/.mount_sonos-njYwR3/resources/app.asar/ui/app.js:5
    (anonymous) @ /tmp/.mount_sonos-njYwR3/resources/app.asar/ui/app.js:7
    Module._compile @ internal/modules/cjs/loader.js:967
    Module._extensions..js @ internal/modules/cjs/loader.js:1004
    Module.load @ internal/modules/cjs/loader.js:815
    Module._load @ internal/modules/cjs/loader.js:727
    Module._load @ electron/js2c/asar.js:769
    Module.require @ internal/modules/cjs/loader.js:852
    require @ internal/modules/cjs/helpers.js:74
    (anonymous) @ window.html:15
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/app.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/Application.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/index.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/SonosServiceReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/constants/index.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/constants/Constants.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/GroupManagementReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/CurrentTrackReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/VolumeControlReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/QueueReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/BrowserListReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/constants/BrowserListConstants.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/MusicServicesReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/MusicServiceClient.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/SonosService.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/helpers/getServiceLogoUrl.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/enhanced/Discovery.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/enhanced/SonosEnhanced.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/enhanced/DevicePropertiesEnhanced.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/enhanced/RenderingControlEnhanced.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/enhanced/ContentDirectoryEnhanced.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/enhanced/GroupRenderingControlEnhanced.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/enhanced/ListenerEnhanced.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/SonosServiceActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/helpers/sonos.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/ZoneGroupSelectors.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/PlaylistReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reducers/EqReducer.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/services/IpcService.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/CurrentTrack.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/CurrentTrackExpanded.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/AlbumArt.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/helpers/dom-utility.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/CurrentTrackCollapsed.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/CurrentTrackNoMusic.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/CurrentTrackSelectors.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/CurrentTrackActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/QueueList.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/QueueListItem.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/QueueActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/helpers/getSelectionSeries.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/PlaylistActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/BrowserListActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/QueueSelectors.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/BrowserList.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/BrowserListItem.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/BrowserListSelectors.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/PlayControls.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/PlayerActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/PlayerSelectors.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/PositionInfo.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/VolumeControls.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/MuteButton.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/ValueSlider.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/VolumeControlActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/EqActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/GroupManagementSelectors.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/VolumeControlSelectors.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/ZoneGroupList.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/ZoneGroup.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/ZoneGroupPlayState.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/ZoneGroupMember.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/ZoneGroupActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/GroupManagement.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/GroupManagementNode.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/GroupManagementActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/MusicServiceManagement.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/reduxActions/MusicServicesActions.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/PlaylistManagement.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/PlaylistManagementAddTrack.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/PlaylistManagementEdit.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/PlaylistManagementSave.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/EqSettings.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/SearchBar.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/SearchBarSources.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/components/Loader.js.map: 
    DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_sonos-njYwR3/resources/app.asar/ui/selectors/LoaderSelectors.js.map:

**Comment by pascalopitz** [comment]
They can just be ignored, yes. I might try and clean them up if i get bored.

**Comment by My-Random-Thoughts** [comment]
Great, thank you.
