### ISSUE TITLE
Google Music and Youtube music cause exception on latest snap

### ISSUE THREAD

**Issue by buelowp** [pascalopitz/unoffical-sonos-controller-for-linux#103]
I just installed Kubuntu 20.04 and tried to run the sonos unofficial using snap. While the app starts and finds the system, clicking on Add New Music Services and then on either Google Play Music or Youtube Music bring up a dialog, but clicking Next has no effect. Clicking on Cancel works. I'm running this from the terminal, and I don't see any debug output or exceptions, but I do see a few startup exceptions, so I can tell that if there was output, I should see it. Other music services seem to work normally. I haven't checked to see which would not be working and which would.

Just letting you know. Everything else seems to be working just fine.

Running on Kubuntu 20.04 on an MB Air (2014) and installed using snapd.

**Comment by pascalopitz** [comment]
See #44 ...
