### ISSUE TITLE
Add and Remove Sonos Favourites

### ISSUE THREAD

**Issue by alex4buba** [pascalopitz/unoffical-sonos-controller-for-linux#106]
I am a Sonos user for the past 6 years (in Windows) and have move to Linux Ubuntu.
Tried, NOSON, didn't like it, now I am trying your app.

It looks good and much closer to what I was used to under Windows, just ffound one problem.

In My Windows time, I had a local music library, this shows now in the list of favourites but of course, no longer exists. It is pointing to my Storage device on Windows. 

How can I remove it from the list? In the attached screenshot - it is the the one on the top of the list

Thank you
Alex
![Screenshot_20200830_082138](https://user-images.githubusercontent.com/31882591/91647095-e9b3ec00-ea99-11ea-9def-69b83aa3e84a.png)

**Comment by pascalopitz** [comment]
Fair point. Need a mechanism to add and remove favourites.

**Comment by pascalopitz** [comment]
As of v0.2.1-alpha8 you should have a menu item that lets you remove sonos favourites
