### ISSUE TITLE
Cannot select music source

### ISSUE THREAD

**Issue by lloyda** [pascalopitz/unoffical-sonos-controller-for-linux#108]
First, let me just say great app, just what I'm looking for.  I've come across a few things, and will open these as separate issues. 

Running on Raspberry Pi, version, running 0.2.1-alpha7-armv7l AppImage (the snap version does not work, get a blank, grey window) on buster.

The first problem I have is that it is almost impossible to select a music source using the touch screen. An individual track is ok, but selecting a whole album or some other source where you have to interact with a pop up menu just does not work - the menu is on the screen for far too short a time.  It pops up and vanishes before you have time to select from it.  If I use a mouse, its fine, the pop up stays there until you interact with it.

For info, there is almost the opposite issue with the volume pop-up - I can't get it to go away - but I'll log that separately

I'm not sure if this is an application issue or a config issue with the Pi.

**Comment by pascalopitz** [comment]
I think we're getting a bit niche here, in terms of exact device configuration support. Touch screen works fine on Ubuntu 20.04 and I can interact with volume and track menus fine.

Feel free to submit pull requests though.

**Comment by pascalopitz** [comment]
Ok, correction. I can interact with the track menus via touch screen as long as it's the first one in the list and highlighted already. This can be improved, maybe. I made this into #110
