### ISSUE TITLE
Does not handle TuneIn radio well

### ISSUE THREAD

**Issue by lloyda** [pascalopitz/unoffical-sonos-controller-for-linux#109]
Is TuneIn supported, as I have a couple of issues.

Firstly, it does not appear in  my list of music sources (it does in the other apps I use with Sonos).

Secondly, if I do select a radio station from TuneIn as a music source from my favourites, it does not seem to be handled quite correctly, as not only does the screen in this app display wrong track, image, next etc. info wrongly, it also causes other apps to also display things wrong. 

I can probably grab you some screen shots if it helps.

**Comment by lloyda** [comment]
Something else I have noticed is that the radio station is added to the queue, which is not the behaviour I would expect.

**Comment by pascalopitz** [comment]
You can add TuneIn as a service.

**Comment by lloyda** [comment]
But I already have TuneIn as a service, which shows on the other apps that I can use to control Sonos.  

Are you suggesting I need to add it again with this app?

**Comment by pascalopitz** [comment]
Yes.

This comes down to the way credentials for the SMAPI services are stored on the Sonos devices and apps. Those have an encrypted exchange going on which no other party is privy to, and in order to use the same services we essentially need to re-authenticate them to obtain a valid auth token.

**Comment by lloyda** [comment]
I'm surprised, because other apps (noson and Zonos) I have not had to add TuneIn, but it does appear in the My Services list.

**Comment by pascalopitz** [comment]
They basically made TuneIn an exception and default added it, which is only possible because that particular service does not require auth. I personally prefer it not being on the list in the first place, that's why I left it off.

**Comment by lloyda** [comment]
I think I'm starting to understand why I am seeing issues.

If I select a radio station from the TuneIn service, it tends to behave correctly.  There is a sensible display of Track and Next is blank, and nothing gets added to the queue.

However, I tend to use Sonos Favourites a lot, and have a few radio stations listed there.  The app seems to assume that everything listed is a track, or maybe an album, but not a radio stream.  So when I select Play Now for a radio stream in Favourites, it does not treat it as a stream, so it displays unexpected strings for Track and Next (which is meaningless when listening to a stream), and also puts the stream onto the queue.

**Comment by pascalopitz** [comment]
Can you please attach a state dump file?

**Comment by lloyda** [comment]
Here you go

[unoffical-sonos-controller.appState.json.gz](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/5283632/unoffical-sonos-controller.appState.json.gz)

**Comment by pascalopitz** [comment]
Ok, I've pushed v0.2.1 which should contain a fix for this
