### ISSUE TITLE
Pandora

### ISSUE THREAD

**Issue by jadenPete** [pascalopitz/unoffical-sonos-controller-for-linux#11]
I don't see Pandora in the list of music sources. How can I play music from Pandora?

**Comment by pascalopitz** [comment]
In this app you can't yet. In the official client, pandora and rdio have a
special status and i think they don't use the standard smapi wsdl.

**Comment by jadenPete** [comment]
OK thank you

**Comment by pascalopitz** [comment]
Ok, it looks like pandora could be implemented by following this info: https://6xq.net/pandora-apidoc/json/partners/

**Comment by jadenPete** [comment]
That's awesome! Let me know if you get any progress

**Comment by pascalopitz** [comment]
Ok, so I made zero progress on this. It's full of special cases and stuff that I couldn't unlock somehow. Then I got this today:

![image](https://user-images.githubusercontent.com/271740/28416134-dbfe00a6-6d91-11e7-997a-f90789f142c6.png)

No love lost.

**Comment by jadenPete** [comment]
Unless you live in Australia or New Zealand, I don't know if its much of an issue.

**Comment by pascalopitz** [comment]
Which I am.

**Comment by CyberManifest** [comment]
If it helps, here in America, I played Pandora on the official app on another device, paused it and was able to resume it on the unofficial app on a different device. So I'm able to control Pandora if it's what's currently playing, but not able to select it as a choice or re-initiate it after selecting another service such as Spotify.

**Comment by CyberManifest** [comment]
I also just discovered that I'm able to save the Pandora stations in my Sonos favorites from the other device and then accesses them on the Linux machine and play them from the unofficial-sonos-controller. Allowing a sort of work around.
