### ISSUE TITLE
Sonos Bridge shows up as a speaker

### ISSUE THREAD

**Issue by bmn001** [pascalopitz/unoffical-sonos-controller-for-linux#112]
I have a Sonos Bridge on my network.  It incorrectly shows up within USCL as a "room" right along with all of my other speakers.

**Comment by pascalopitz** [comment]
Can you take a state dump via the developer menu and attach it here plz, so I can see what needs excluding?

**Comment by PiperKev** [comment]
I have the same issue with my Boost.  It shows up as a "room" with my other speakers.
![Screenshot from 2020-11-25 13-24-03](https://user-images.githubusercontent.com/8465037/100267702-d6da7780-2f21-11eb-9e73-1980dbe07dc7.png)

**Comment by PiperKev** [comment]
I have a similar issue, except it's my Boost that shows up as a "room".  I tried to attach my app state as a file, but github doesn't seem to accept .json files.  I can insert it as plain text, if that'll work!

**Comment by pascalopitz** [comment]
You can zip it and attach

**Comment by PiperKev** [comment]
[unoffical-sonos-controller.appState.json.zip](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/5599611/unoffical-sonos-controller.appState.json.zip)

**Comment by pascalopitz** [comment]
Fixed? https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.2.2

**Comment by PiperKev** [comment]
That did it!!  Thanks!!
