### ISSUE TITLE
Request: Add ability to Enable Wi-Fi / Disable Wi-Fi like in the mobile app

### ISSUE THREAD

**Issue by ObeliskCo** [pascalopitz/unoffical-sonos-controller-for-linux#118]
So this might well be a request that not many are interested in, but I'll throw it out there anyway!  Users and systems integrators used to have access to a rich command set using the unofficial web interface for Sonos products (http://<Device IP>:1400/<command>).  For example: we could reboot a device, check various status items, and best of all enable and/or disable the device's wifi interface.  This command set has been drastically reduced to only some basic status checking, but for us systems integrators out there, the ability to enable/disable wifi from UnSoCo would be HUGE.  The reason for this is that the correct way to install wired Sonos units is to disable wifi on them (some exceptions-- no flames pls!), and recently some Sonos updates have re-enabled wifi on devices that previously had it disabled, causing network loops and unhappy clients.  In this scenario, it almost always requires a site visit to resolve because only the Sonos app can toggle wifi, and (1) walking a client through this can be undesirable and (2) connecting to the problematic Sonos devices reliably once a network loop has been created can often be impossible (requiring on-site power cycling of the devices individually in order to toggle the wifi, then proceed to the next devie, etc.).  It would simply be AMAZING to have this feature re-accessible for remote support by having UnSoCo running on a RPi, which we often install as part of our standard network installations for various maintenance tasks.  I would be happy to help in any way possible.  Thank you for all you have done on this fantastic version of a controller.

**Comment by pascalopitz** [comment]
I'll need some more info here. Is this per device or for the whole system? What is the Service call used for it? Where in the UI should it live?

**Comment by pascalopitz** [comment]
Closed due to lack of feedback

**Comment by ObeliskCo** [comment]
Pascal—I am SO sorry for the delay in replying.  How should I send you 4 screenshots to show the process?

HUGE THANKS!!

---------------------------
Charles von Mueffling
OBELISK CONSULTING, INC.
171 Madison Avenue, Suite 1333
New York, NY 10016
212-563-1700
Charlie@ObeliskConsulting.com<mailto:Charlie@ObeliskConsulting.com>
P Please consider the environment before printing this email
