### ISSUE TITLE
Add Manual IP Dialog closes on its own

### ISSUE THREAD

**Issue by motoridersd** [pascalopitz/unoffical-sonos-controller-for-linux#119]
I run my Sonos speakers on a separate VLAN, and even though most of my services can find them across VLANs sthrough PIMD and Avahi, this app cannot. 

No biggie, I just need to add the speaker IPs manually. Unfortunately, when I try to use the Developer - Add IP Manually option, I see the dialog pop up but it disappears right away. 

Where can I edit this manually in a config file? I was able to export the settings but I don't see what the app is expecting this value to be in order for me to import it. I was unable to find where in the snap files this is saved.

Is there an easy way to do it without the app?

App state below:

{
    "appState": {
        "sonosService": {
            "currentGroup": null,
            "currentHost": null,
            "zones": [],
            "deviceSearches": {},
            "albumArtCache": {},
            "currentTracks": {},
            "nextTracks": {},
            "positionInfos": {},
            "playStates": {},
            "playModes": {},
            "crossFadeModes": {}
        },
        "groupManagement": {
            "selected": [],
            "visible": false,
            "current": null
        },
        "currentTrack": {
            "expanded": true
        },
        "volume": {
            "dragging": false,
            "expanded": false,
            "volume": {},
            "muted": {}
        },
        "queue": {
            "currentHost": null,
            "currentGroup": null,
            "playerItems": {},
            "selected": []
        },
        "browserList": {
            "source": null,
            "searchTerm": null,
            "searchMode": "artists",
            "history": [
                {
                    "source": "start",
                    "searchType": null,
                    "title": "Select a Music Source",
                    "items": [
                        {
                            "title": "Sonos Favourites",
                            "searchType": "FV:2",
                            "albumArtURI": "./svg/ic_favorite_48px.svg"
                        },
                        {
                            "title": "Music Library",
                            "action": "library",
                            "albumArtURI": "./svg/ic_audiotrack_48px.svg"
                        },
                        {
                            "title": "Sonos Playlists",
                            "searchType": "SQ:",
                            "albumArtURI": "./svg/ic_featured_play_list_48px.svg"
                        },
                        {
                            "title": "Line-in",
                            "action": "linein",
                            "albumArtURI": "./svg/ic_input_48px.svg"
                        }
                    ]
                }
            ]
        },
        "musicServices": {
            "active": [],
            "visible": false,
            "link": null,
            "current": null
        },
        "playlists": {
            "mode": null,
            "visible": false,
            "item": null,
            "playlists": [],
            "selected": [],
            "items": []
        },
        "eq": {
            "visible": false,
            "host": null,
            "eqState": {}
        }
    },
    "packageJson": {
        "name": "sonos-controller-unofficial",
        "description": "Unoffical sonos controller for linux.",
        "version": "0.2.1",
        "author": "Pascal Opitz <contact@pascalopitz.com>",
        "main": "main.js",
        "dependencies": {
            "array-union": "^2.0.0",
            "bluebird": "^3.5.4",
            "classnames": "^2.2.6",
            "deep-equal": "^2.0.3",
            "dotenv": "^8.2.0",
            "electron-prompt": "^1.6.0",
            "file-type": "^15.0.1",
            "ip": "^1.1.5",
            "koa": "^2.13.0",
            "koa-bodyparser": "^4.3.0",
            "koa-logger": "^3.2.1",
            "koa-router": "^9.4.0",
            "lodash": "^4.17.20",
            "mask-json": "^1.0.3",
            "mime": "^2.4.6",
            "moment": "^2.29.0",
            "music-metadata": "^7.4.0",
            "omit-keys": "^0.1.0",
            "react": "^16.13.1",
            "react-dom": "^16.13.1",
            "react-redux": "^7.2.1",
            "react-tiny-virtual-list": "^2.2.0",
            "react-viewport-list": "^3.0.0",
            "react-virtual-list": "^2.3.0",
            "react-virtualized-auto-sizer": "^1.0.2",
            "redux": "^4.0.1",
            "redux-actions": "^2.6.5",
            "redux-promise": "^0.6.0",
            "reselect": "^4.0.0",
            "shallow-compare": "^1.2.2",
            "sonos": "^1.15.0-alpha.1",
            "sql.js": "^1.3.0",
            "uuid": "^8.3.0",
            "wake-event": "^0.0.1",
            "walkdir": "^0.4.1"
        }
    }
}

**Comment by pascalopitz** [comment]
Right now a config file entry is not possible. The menu option should not just vanish though. What OS/desktop/environment are you using?

**Comment by havanahjoe** [comment]
I'm on Pop!_OS 20.10, which runs Gnome 3.38.1

**Comment by quamok** [comment]
new user here, fresh install. I Have the same issue. The popup quickly flashes then disapear. Running Linut Mint latest version.

**Comment by PiperKev** [comment]
Same issue here, running Linux Mint 20.  The IP Address window pops up, then disappears.

**Comment by pascalopitz** [comment]
The library I use for this is https://github.com/p-sam/electron-prompt. I'll file an issue.

**Comment by adamcstephens** [comment]
I'm experiencing the same issue on Opensuse Tumbleweed running Sway.

**Comment by adamcstephens** [comment]
I've confirmed this on both the RPM and the appimage. 

Running the repo in develop mode works as expected and allows entry through the popup.

**Comment by AureliaSpatz** [comment]
How do I run it in develop mode?

**Comment by pascalopitz** [comment]
https://github.com/pascalopitz/unoffical-sonos-controller-for-linux#and-run-locally

**Comment by AureliaSpatz** [comment]
linux@localhost:~> npm run develop
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/linux/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/linux/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linux/.npm/_logs/2021-03-05T22_02_17_007Z-debug.log

(I'm on openSUSE Leap 15.2. and have downloaded the AppImage.)

**Comment by pascalopitz** [comment]
Sorry, I thought this is obvious, You will need to clone the code repository and execute the commands inside that directory. The AppImage is a packaged up artefact.

**Comment by bobfredarctor** [comment]
I have the same problem on Ubuntu 20.04
Also latest version (0.2.3) doesn't find the system even if firewall is disabled. I had to install 0.2.1 to connect.

**Comment by AureliaSpatz** [comment]
> Sorry, I thought this is obvious, You will need to clone the code repository and execute the commands inside that directory. The AppImage is a packaged up artefact.

Thank you, I have now managed to get it to work :-) 

openSUSE doesn't know gh, so I had to download the zip. (I know this is nothing to do with your project, just a note.)

Do I always have to start it from terminal with "npm run develop" or is there a way to get it into the application launcher? I'd prefer not to have yet another terminal window lying around.
Every time I start it with "npm run develop" it again keeps searching for my Sonos system and doesn't find it so I have to add the IP manually. Is there a way to get it to remember this IP?

**Comment by pascalopitz** [comment]
@bobfredarctor There was a problem with the build artefact. I have yanked and re-published v0.2.3 ... should load okay now.

As for the IP dialog: Yep, reproducing it as well now, but only in a generated artefact.

**Comment by bobfredarctor** [comment]
> @bobfredarctor There was a problem with the build artefact. I have yanked and re-published v0.2.3 ... should load okay now.
> 
> As for the IP dialog: Yep, reproducing it as well now, but only in a generated artefact.

Both IP dialog and connection works with latest release now.

**Comment by motoridersd** [comment]
Awesome. Can confirm this works for me too. Once the controller finds one speaker via manual IP, it can talk to all others on a separate VLAN
