### ISSUE TITLE
Play from File / Music Library Empty

### ISSUE THREAD

**Issue by jadenPete** [pascalopitz/unoffical-sonos-controller-for-linux#12]
I have a music library composed of MP3's and FLAC's, but it is stored on my Windows Partition. I have changed the path in `~/.config/user-dirs.dirs` to reroute my Music directory to this. But when I click Music Library, everything shows empty, no matter if I click Albums, Tracks, Artists, etc.

**Comment by pascalopitz** [comment]
The music library in sonos speak is a network mounted drive indexed by the
sonos devices. You can add this to your system using an official client.
I am also working on streaming local music, but its under development. It
will say "on this device"

**Comment by pascalopitz** [comment]
That said, I'll open a different ticket to enable the app managing the music library's indexed smb:// accessible stores

**Comment by jadenPete** [comment]
Oops I thought it meant local files

**Comment by pascalopitz** [comment]
Maybe I should compose an FAQ, this question came up quite a bit when it was still in the chrome store

**Comment by jadenPete** [comment]
Yeah that would be a good idea. This would be helpful for new users looking to use Sonos on Linux.
