### ISSUE TITLE
Flatpak Release

### ISSUE THREAD

**Issue by ChrisWiegman** [pascalopitz/unoffical-sonos-controller-for-linux#120]
Would it be possible to get a Flatpak release to be able to easily manage dependencies for those of us not using a snap-based distro?

**Comment by pascalopitz** [comment]
Flatpak doesn't seem to be supported by [electron builder](https://www.electron.build/configuration/linux#LinuxConfiguration-target)?
You could use the AppImage?

**Comment by nekohayo** [comment]
Flatpaks can be built with electron builder as far as I can tell: see https://docs.flatpak.org/en/latest/electron.html ? There's also https://www.electronforge.io/config/makers/flatpak and https://github.com/endlessm/electron-installer-flatpak, I don't know if those end up being the same.

**Comment by mmrezaie** [comment]
Can someone more knowledgable review this again if we can use flatpak?
