### ISSUE TITLE
Opening Sonos Controller on Raspberry Pi

### ISSUE THREAD

**Issue by DJT1423** [pascalopitz/unoffical-sonos-controller-for-linux#121]
I have installed your Snapd Sonos unofficial  controller  on Raspberry Pi, however it doesn't appear in the applications  menu, and I don't see how to open the Controller. Can you help?

**Comment by stan-qaz** [comment]
I just download the sonos-controller-unofficial-0.2.2-armv7l.AppImage file to my Pi 3b+, set the permissions to allow execute, click it from the file manager and choose Execute and it runs.

**Comment by pascalopitz** [comment]
Sorry, I cannot support individual platform issues for Snap
