### ISSUE TITLE
How to display any sounds from the computer

### ISSUE THREAD

**Issue by smaimon** [pascalopitz/unoffical-sonos-controller-for-linux#124]
Hi there,
I wondering how can I play any sounds from my computer ?
For example I use to watch movies  through Firefox or VLC media player. 

Thank you to the team for this helpful project 👍

**Comment by pascalopitz** [comment]
You will need another project to do that. I think https://github.com/pascalopitz/budgie-stream is aiming to achieve that, but I couldn't get it to work on Linux.
