### ISSUE TITLE
Squares instead of characters in some dialogs

### ISSUE THREAD

**Issue by troelsarvin** [pascalopitz/unoffical-sonos-controller-for-linux#125]
When I try to use the "Set local music folder" menu item, the resulting pop-up window contains squares instead of characters. The application was installed via snap. Version of the application: 0.2.2.

![sshot](https://user-images.githubusercontent.com/5257280/107863656-4b082580-6e56-11eb-83b2-f8da0d8c3fc1.png)

Operating system: Fedora 33.

**Comment by pascalopitz** [comment]
Same if you use app image?

**Comment by troelsarvin** [comment]
No, there isn't a problem with the AppImage version, so I can try using that.

(But as far as I know, AppImage installations will not automatically be updated, so I'm not a fan of AppImage.)

**Comment by pascalopitz** [comment]
Electron builder is what I am using to create the individual binaries. Not sure why snap would be different?

**Comment by pascalopitz** [comment]
Related? https://github.com/electron-userland/electron-builder/issues/5217

**Comment by troelsarvin** [comment]
That's very possibly related. The RPM file doesn't have the font issues, either, by the way.
If it's an Electron+Snap combination issue, then I suppose there isn't much which can be done about it in this ticket, so maybe it should be closed.

**Comment by pascalopitz** [comment]
Looks like it's got nothing to do with my code. If the snap install is flagging more problems, I might actually remove that distribution channel all together,
