### ISSUE TITLE
Searches containing spaces return no results

### ISSUE THREAD

**Issue by D661** [pascalopitz/unoffical-sonos-controller-for-linux#126]
Searching the music library with a search string containing spaces return no results.

I can search for "Let", "it", or "be", but not for "Let it be".

I'm using version 0.2.2 on Linux Mint 19.3, installed via snap.

**Comment by pascalopitz** [comment]
Fixed as of v0.2.3

**Comment by D661** [comment]
Working great for me. Thank you for the fix!

**Comment by pascalopitz** [comment]
Fix was a one liner. Deploying it however ... I seem to work on the app in
intervals where in between some dependencies move on or break and I have to
debug deployment all over again ...
