### ISSUE TITLE
"Add IP manually" window disappears immediately

### ISSUE THREAD

**Issue by kalsan** [pascalopitz/unoffical-sonos-controller-for-linux#127]
When clicking "Add IP manually", a small window with the title "Add IP manually" opens up and disappears immediately. The window is empty.

Version: 0.2.2
Installed from .deb
Window manager: i3

Best,
Kalsan

**Comment by My-Random-Thoughts** [comment]
This is a duplicate of #119.

**Comment by kalsan** [comment]
Thanks, closing this issue
