### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by woutgg** [pascalopitz/unoffical-sonos-controller-for-linux#133]
First of all I'd like to say that this is a very nice application! It's really invaluable to have on Linux.

It is somewhat impractical however, that I have to move and resize the application window every time I start the program.
So it would be very nice if those things (position+size) were restored on restart.

**Comment by pascalopitz** [comment]
Possible solution: https://medium.com/@hql287/persisting-windows-state-in-electron-using-javascript-closure-17fc0821d37

**Comment by woutgg** [comment]
Looks good! Some thoughts:

- I'm not sure if move/resize event rate will be an issue (machine/os dependent?), but it might be good to throttle the 'resize' and 'move' callbacks in the `track` function.
- I think it would be nice if the code properly deals with (dis)appeared monitors and changed screen resolutions. This could be as simple as checking window bounds against display bounds ([API here](https://www.electronjs.org/docs/api/screen)) and capping/moving as necessary.

If I find the time I'm happy to have a go at this (or the other issue I opened), but I'm not sure how soon that will be.

**Comment by woutgg** [comment]
Nice, thank you!
