### ISSUE TITLE
Device discovery cannot find Sonos

### ISSUE THREAD

**Issue by mikerjensen** [pascalopitz/unoffical-sonos-controller-for-linux#137]
I'm a first time user, downloaded the latest version of the .deb to a recent install of Xubuntu 20.10, checked I have the other suggested packages, and the app simply sits indefinitely searching for the Sonos. The noson-app running on the same machine finds it fine.  I tried entering the Sonos' IP address into the app but after filling the field, there is no response to clicking on the 'OK' box. The output from the console is:
j@x260:~$ sonos-controller-unofficial 
(node:11273) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

I've disabled ufw, same behaviour

Any suggestions what to try next?

**Comment by pascalopitz** [comment]
If you know the IP of one of the players, you could try and add it manually
via the "Developer" menu option.

**Comment by mikerjensen** [comment]
I actually tried that, but as soon as I click on OK, that field locks up, can't be edited...nothing else changes.

**Comment by pascalopitz** [comment]
I really don't know then. Don't run Xubunutu. Anyone?

**Comment by juh** [comment]
Not of much help, but version 0.2.5 runs fine on my Kubuntu 20.04.

**Comment by mikerjensen** [comment]
Strangely, it just started working when i tried it again this morning. No changes to the system that I am aware of. Sorry for the bother.
