### ISSUE TITLE
i'm a noob

### ISSUE THREAD

**Issue by POP24** [pascalopitz/unoffical-sonos-controller-for-linux#139]
Hello, thanks for this app.
I've successfull install  sonos-controller-unofficial (edge) 0.2.5 on my rasberrypi , 
but as usual, i dont know how to launch the application right now ?
I dont know how to find the correct launching name or app icone xD 

Thx for your help.

**Comment by pascalopitz** [comment]
No idea, I don't use a raspberry pi ... maybe run `updatedb` and then `locate`?

**Comment by bouton** [comment]
FYI for thse whoc come later
I just added this to my raspberry pi 3 using snapd and latest raspberry OS. Also a noob. With a bit of searching I got it to run via terminal /snap/bin/sonos-controller-unofficial
Ignored error messages and all seems to work fine.
