### ISSUE TITLE
Cannot see Spotify content

### ISSUE THREAD

**Issue by peteygreen** [pascalopitz/unoffical-sonos-controller-for-linux#141]
Hi!

Great application! Installed it yesterday. I added Spotify as a music service. It shows up in the list of music services, but when I click the Spotify icon there’s a short glimpse of playlists in the same section section of the screen but then it goes blank. I can (sometimes) click to go back to the list of music services, and other times the section just remains blank.

Scratching my head. Help? :)

**Comment by pascalopitz** [comment]
Can you attach a state dump file please, and maybe a screen recording?

**Comment by peteygreen** [comment]
Hi Pascal,

Thanks for replying!

Here's the app state:
[unofficial-sonos-state--2021-06-14.txt](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/6650164/unofficial-sonos-state--2021-06-14.txt)

**Comment by peteygreen** [comment]
And here's the video recording:

https://user-images.githubusercontent.com/85824253/121934359-830d6f80-cd47-11eb-8ad6-6c4fa2d57977.mov

All the best,

Petter

**Comment by pascalopitz** [comment]
Hmm, this looks odd. Can you fire up the inspector and check the console for error messages?

**Comment by peteygreen** [comment]
Hi Pascal,

I've attached two files. One extracted at startup, and the other after having called Spotify. Let me know if you need more information. /Petter

[consol_1.log](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/6722164/consol_1.log)
[consol_2.log](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/6722165/consol_2.log)

**Comment by peteygreen** [comment]
Great work! Thanks!

Petter

Skickat från min iPhone
