### ISSUE TITLE
endless discovery till entering ip

### ISSUE THREAD

**Issue by baahver** [pascalopitz/unoffical-sonos-controller-for-linux#143]
Ubuntu 20.10 Laptop. 
UFW enabled, and tested with disabled firewall.
sonos ufw rule: 
`ports=80,443,445,1400:1410,3400,3401,3405,3445,3500,4000,4070,4444/tcp|136,137,138,139,1900,1901,2869,10243,10280,10281,10282,10283,10284,5353,6969/udp|40000:60000/udp|35382`
(If I add udp 1905 ufw gives an error. But disabling ufw does not differ)

Both laptop and sonos 1, 5 and move are in the same subnet 192.168.188.x
Tried both snap version en deb version.

When starting unofficial sonos controller discovery starts: searching for sonos systems.
It will not find them. 
Everytime I enter the ip-address of the 5 or Move, the 3 sonos systems are found.

Anything I can do?

**Comment by baahver** [comment]
Does the app state file contain credentials or other information I should blackout?

**Comment by pascalopitz** [comment]
This is down to your network somehow, and the devices not receiving or sending through the response to the Multicast correctly. Impossible for me to debug. The good news is that the manual IP works :)

**Comment by pascalopitz** [comment]
Also, to answer your question about app state file: AuthTokens get redacted on export.
