### ISSUE TITLE
Cannot find Sono System

### ISSUE THREAD

**Issue by uneewk** [pascalopitz/unoffical-sonos-controller-for-linux#145]
I have version 0.6.5 installed on Elementary OS 5.1.7 Built on Ubuntu 18.04.4 When I start the controller, I get "Searching for your Sonos Controller" and it never finds it. Any ideas on what I can do to troubleshoot and figure out what is going wrong? Thanks for your help.

**Comment by pascalopitz** [comment]
https://github.com/pascalopitz/unoffical-sonos-controller-for-linux#troubleshooting
