### ISSUE TITLE
Searching for a specific album title only returns one result when four exists.

### ISSUE THREAD

**Issue by My-Random-Thoughts** [pascalopitz/unoffical-sonos-controller-for-linux#147]
I have logged a bug and adding info to a ticket for a NodeRED addon that I use.  It has the issue listed above and during my testing it turns out that your software also has this same issue

https://github.com/hklages/node-red-contrib-sonos-plus/issues/161

Can you have a look to see if it's a "you" problem too, or with how the Sonos is returning data to you.

Thanks

**Comment by pascalopitz** [comment]
That's a Sonos issue itself.
