### ISSUE TITLE
Regular crash with Javascript error

### ISSUE THREAD

**Issue by alex4buba** [pascalopitz/unoffical-sonos-controller-for-linux#149]
When my PC goes to slip (Linux - KDE Neon Plasma 5.22.4), it comes up with : Searching for your SONOS System and the only way to get back is to reboot my PC.

**Comment by pascalopitz** [comment]
Next time just refresh with CTRL+R and see how that goes?

**Comment by pascalopitz** [comment]
Closed because no reply ^

**Comment by alex4buba** [comment]
Thanks for the tip, it seems a problem resolved by an update of the SONOS software
Cheers
Alex
