### ISSUE TITLE
Music will not play

### ISSUE THREAD

**Issue by Alveerd** [pascalopitz/unoffical-sonos-controller-for-linux#153]
The controller opens, it sees my Sonos system, and it sees the music library. Once I place music into the queue, I cannot get the music to play. Play button does nothing. Running Ubuntu 21.04.1. Any help is appreciated.

**Comment by pascalopitz** [comment]
You'll have to give me a bit more context than that. State dump? Some debug console messages? Anything?

**Comment by pascalopitz** [comment]
Closed because no reply ^
