### ISSUE TITLE
Stuck in "Searching for your Sonos System"

### ISSUE THREAD

**Issue by mengwangsonos** [pascalopitz/unoffical-sonos-controller-for-linux#159]
[Failed to find device.log](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/7287833/Failed.to.find.device.log)

**Comment by pascalopitz** [comment]
Probably a networking issue, with the Multicast UPNP announcement not getting through to the devices for some reason. Nothing I can do here as it's impossible for me to debug your networking particulars. If you know the devices IP you can try adding it manually via the Developer menu
