### ISSUE TITLE
spotify service shown twice in right pane

### ISSUE THREAD

**Issue by jkall** [pascalopitz/unoffical-sonos-controller-for-linux#16]
First of all, thank you for this application! It is really great.

This is of minor importance, but still an unexpected behaviour: I do get the spotify service shown twice in the right pane. Both entrances seem to work. i.e. I can enter spotify interface by double-clicking any of the two spotify services in the pane.

![image](https://cloud.githubusercontent.com/assets/6205804/21892589/d5404e8a-d8d7-11e6-88f4-905e55773d56.png)

**Comment by pascalopitz** [comment]
Can't you just remove one?

**Comment by jkall** [comment]
No, then both services are removed.

**Comment by jkall** [comment]
It might be a coincidence but I can not see this issue after installing release v0.0.10.
