### ISSUE TITLE
0.3.0-alpha1 Does not find my Sonos.

### ISSUE THREAD

**Issue by stan-qaz** [pascalopitz/unoffical-sonos-controller-for-linux#168]
Giving 0.3.0-alpha1 a quick look and it does not find my Sonos System. 

Version 2.9 on the same system works fine.

**Comment by pascalopitz** [comment]
How did you fire it up? App image? Deb?

**Comment by stan-qaz** [comment]
On a Raspberry Pi 3B, the Arm x7l Appimage.

Sorry for the lack of info, if you need anything more I'll try to add it.

Starting from the Terminal:

[1593:1219/192913.388236:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[1633:1219/192914.555434:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

=============
Main controller window opened with the developer tools window open, this is the Console output from there.

react-dom.development.js:67 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: VirtualList
SonosService.js:436 onVolumeEvent 172.16.1.130 7
SonosService.js:426 onMutedEvent 172.16.1.130 false
SonosService.js:411 onRenderingControlEvent 172.16.1.130 
{val: '0', Volume: Array(3), Mute: Array(3), Bass: {?}, Treble: {?}, ?}
SonosService.js:396 onZoneGroupTopologyEvent 172.16.1.113 
(4) [SonosGroup, SonosGroup, SonosGroup, SonosGroup]
SonosService.js:436 onVolumeEvent 172.16.1.114 9
SonosService.js:426 onMutedEvent 172.16.1.114 false
SonosService.js:411 onRenderingControlEvent 172.16.1.114 
{val: '0', Volume: Array(3), Mute: Array(3), Bass: {?}, Treble: {?}, ?}
SonosService.js:396 onZoneGroupTopologyEvent 172.16.1.113 
(4) [SonosGroup, SonosGroup, SonosGroup, SonosGroup]
SonosService.js:396 onZoneGroupTopologyEvent 172.16.1.113 
(4) [SonosGroup, SonosGroup, SonosGroup, SonosGroup]
SonosService.js:451 onCurrentTrackEvent 172.16.1.110 
{id: null, parentID: null, title: 'Carol Of The Birds', artist: 'Mannheim Steamroller', album: 'Christmas Celebration', ?}
SonosService.js:461 onNextTrackEvent 172.16.1.110 
{id: null, parentID: null, title: 'Hark The Herald Angels Sing', artist: 'Willie Nelson & Bobbie Nelson', album: 'Hill Country Christmas', ?}
SonosService.js:446 onPlayStateEvent 172.16.1.110 playing
SonosService.js:446 onPlayStateEvent 172.16.1.130 playing
SonosService.js:446 onPlayStateEvent 172.16.1.114 playing
SonosService.js:390 onAlarmClockEvent 
{name: 'AlarmClock', eventBody: Array(7)}
SonosService.js:436 onVolumeEvent 172.16.1.113 17
SonosService.js:426 onMutedEvent 172.16.1.113 false
SonosService.js:411 onRenderingControlEvent 172.16.1.113 
{val: '0', Volume: Array(3), Mute: Array(3), Bass: {?}, Treble: {?}, ?}
SonosService.js:436 onVolumeEvent 172.16.1.115 19
SonosService.js:426 onMutedEvent 172.16.1.115 false
SonosService.js:411 onRenderingControlEvent 172.16.1.115 
{val: '0', Volume: Array(3), Mute: Array(3), Bass: {?}, Treble: {?}, ?}
SonosService.js:436 onVolumeEvent 172.16.1.112 10
SonosService.js:426 onMutedEvent 172.16.1.112 false
SonosService.js:411 onRenderingControlEvent 172.16.1.112 
{val: '0', Volume: Array(3), Mute: Array(3), Bass: {?}, Treble: {?}, ?}
SonosService.js:436 onVolumeEvent 172.16.1.120 12
SonosService.js:426 onMutedEvent 172.16.1.120 false
SonosService.js:411 onRenderingControlEvent 172.16.1.120 
{val: '0', Volume: Array(3), Mute: Array(3), Bass: {?}, Treble: {?}, ?}
SonosService.js:436 onVolumeEvent 172.16.1.125 32
SonosService.js:426 onMutedEvent 172.16.1.125 false
SonosService.js:411 onRenderingControlEvent 172.16.1.125 
{val: '0', Volume: Array(3), Mute: Array(3), Bass: {?}, Treble: {?}, ?}
SonosService.js:390 onAlarmClockEvent 
{name: 'AlarmClock', eventBody: Array(7)}
SonosService.js:451 onCurrentTrackEvent 172.16.1.113 
{id: null, parentID: null, title: "Help on the Way / Slipknot! / Franklin's Tower (Live October 1989 - April 1990)", artist: 'Grateful Dead', album: 'Without a Net (Live)', ?}
SonosService.js:446 onPlayStateEvent 172.16.1.113 paused
SonosService.js:396 onZoneGroupTopologyEvent 172.16.1.113 
(4) [SonosGroup, SonosGroup, SonosGroup, SonosGroup]
SonosService.js:446 onPlayStateEvent 172.16.1.115 stopped
SonosService.js:390 onAlarmClockEvent 
{name: 'AlarmClock', eventBody: Array(7)}
SonosService.js:390 onAlarmClockEvent 
{name: 'AlarmClock', eventBody: Array(7)}
SonosService.js:446 onPlayStateEvent 172.16.1.112 playing
SonosService.js:446 onPlayStateEvent 172.16.1.120 playing
SonosService.js:446 onPlayStateEvent 172.16.1.125 stopped
SonosService.js:421 onGroupRenderingControlEvent 172.16.1.113 
(3) [{?}, {?}, {?}]
SonosService.js:396 onZoneGroupTopologyEvent 172.16.1.113 
(4) [SonosGroup, SonosGroup, SonosGroup, SonosGroup]
SonosService.js:421 onGroupRenderingControlEvent 172.16.1.115 
(3) [{?}, {?}, {?}]

=========================================
Issue button shows:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
AFFECTED RESOURCES
1 source

=======================
App State won't go to clipboard or save as a file. The save dialog opens and you can tap save but nothing is saved.

**Comment by stan-qaz** [comment]
Update: I left it running the Search while I went on to other things, it looks like it finally did find my system after about 20 minutes. 

Moving on to Alpha 2.

**Comment by pascalopitz** [comment]
I had previously made a change and force updated the same tag, but I am not sure it got published correctly ... I forced re-publishing of all artifacts by bumping the release version, have removed alpha1. Let me know how you go.

Quick tip: When pasting code, logfiles etc, use the triple back tick markdown blocks, it'll be easier to read.
