### ISSUE TITLE
can only play single songs with spotify, not full playlist

### ISSUE THREAD

**Issue by jkall** [pascalopitz/unoffical-sonos-controller-for-linux#17]
I can play single songs from spotify service. But nothing happens when I select "play" or "add to queue".
Console says: 

> 500 (Internal Server Error)request @ request.js:57request @ Sonos.js:51queue @ Sonos.js:634_getItem.then.item @ BrowserListActions.js:170

**Comment by pascalopitz** [comment]
Works for me.
