### ISSUE TITLE
Adding Audible (as a music service) next button does nothing when clicked

### ISSUE THREAD

**Issue by mikepc** [pascalopitz/unoffical-sonos-controller-for-linux#181]
Add music service -> Edge/experimental warning -> Next (nothing happens)

**Comment by pascalopitz** [comment]
I don't use Audible and only really make music services work that I personally use.  Welcome to submit a PR though.

**Comment by pascalopitz** [comment]
Ok, I had a look found a regression for all services. Should be fixed now, as per v0.3.0-alpha4
