### ISSUE TITLE
Don't see GPM accounts

### ISSUE THREAD

**Issue by liamdawson** [pascalopitz/unoffical-sonos-controller-for-linux#19]
I have multiple GPM accounts set up via the official controllers, and when I open the app, I don't see either (but do see the add a service button).

**Comment by pascalopitz** [comment]
So the official sonos app can actually use the already authenticated service accounts. The mechanism of how the authentication is retrieved by the controller is not documented or obvious. Therefore this project double-authenticates the services. They are, however, in a very experimental stage, and GPM is one that I have so far not gotten to work.

**Comment by pascalopitz** [comment]
Ok, if you re-add the service now, it should work?

**Comment by pascalopitz** [comment]
Works for me now
