### ISSUE TITLE
self.emit is not a function error in console

### ISSUE THREAD

**Issue by acyuta108** [pascalopitz/unoffical-sonos-controller-for-linux#26]
Installed latest .deb version [v0.0.11 -  1e632ee](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.0.11)
Application/GUI opens but cannot add sources, change volume (muted) or practically do anything.

/opt/sonos-controller-unofficial/resources/app.asar/js/ui/sonos/Search.js:47 Uncaught TypeError: self.emit is not a function
    at Socket.<anonymous> (/opt/sonos-controller-unofficial/resources/app.asar/js/ui/sonos/Search.js:47:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at _handle.lookup (dgram.js:216:14)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by pascalopitz** [comment]
Is this the first install you tried or new behaviour between latest and a previous install?
Have you checked your firewall settings etc? You need to open up:

TCP 1400 outgoing
TCP 3400 incoming
UDP 1900 outgoing
UDP 1905 incoming

It looks like the UDP multicast announce is failing for some reason. 
https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/blob/master/src/ui/sonos/Search.js#L47

**Comment by pascalopitz** [comment]
No updates ... closing for now
