### ISSUE TITLE
Music Library - Search by composer

### ISSUE THREAD

**Issue by Davethehedgehog** [pascalopitz/unoffical-sonos-controller-for-linux#27]
First - many thanks for this app -I've been running Sonos Controller under Wine and it's somewhat unstable and won't run the more recent versions of Sonos.
My issue is that I enjoy listening to classical music which is stored on my computer by composer. So, if I follow the path Music Library/Folders/My Computer/Classical/Beethoven, I get the subfolders in Beethoven but not the three other tracks that are in the Beethoven folder but not in subfolders.  Hope this makes sense!

**Comment by pascalopitz** [comment]
From a UX perspective, what's the suggestion for search by composer? The search bar is already a bit crowded and could use some TLC I guess. 

![image](https://user-images.githubusercontent.com/271740/27619242-1153f4d4-5c00-11e7-94ed-3983f8ea129d.png)

**Comment by pascalopitz** [comment]
Can you try this: https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.1.0-alpha3

**Comment by pascalopitz** [comment]
I consider this addressed as with the latest pre-release we can search composers as well
