### ISSUE TITLE
Plex Music Service

### ISSUE THREAD

**Issue by aremai** [pascalopitz/unoffical-sonos-controller-for-linux#34]
Hi,

@pascalopitz first of all thanks a lot for working on and maintaining a sonos controller for linux. very much appreciated :)
I've wanted to add a plex music service, but it returned just this empty window without any possibility to enter the credentials.

![screenshot_20170715_200535](https://user-images.githubusercontent.com/6547551/28241674-46e00254-6999-11e7-904c-e70bf58fd41b.png)

Does anyone else get this?

cheers,
theresa

**Comment by pascalopitz** [comment]
Hi, I just pushed a release. See how you go. It will now open the external authentication in the OS default browser, and show the link code required if needed.

The rest of the release is housekeeping stuff, like using a code formatter.

**Comment by pascalopitz** [comment]
Any update on this? Can I close?
