### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by DarkLite1** [pascalopitz/unoffical-sonos-controller-for-linux#37]
Before moving over to Fedora, I was also a vivid Ubuntu user. However, it would be nice to have a snap package of the software available. This allows all linux distributions to use your tool..

More infor here:
[https://snapcraft.io/](https://snapcraft.io/)

**Comment by pascalopitz** [comment]
Unfortunately I have had real trouble getting snapcraft 2 working on travis-ci, so that one is out. I did however add AppImage as build target, hope that addresses the issue somewhat

**Comment by DarkLite1** [comment]
Thanks for the feedback, really appreciate the effort. Did some research for you and it seems things have changed now and integration with Travis should be possible. Please have a look here:
- [Continuous snap delivery from Travis CI](https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci#0), found this [here](https://forum.snapcraft.io/t/support-snaps-in-travis-trusty/421/7).

Hope this helps you in adding Snaps.

**Comment by pascalopitz** [comment]
Yes, I saw that. How this fits in with electron builder though is not quite
clear to me yet. Will address some other issues first, then have a fresh
look at it.

**Comment by pascalopitz** [comment]
I have just moved over to github actions instead of travis ci, and am able to publish to snapcraft.

`snap install --edge sonos-controller-unofficial`
