### ISSUE TITLE
apple music 

### ISSUE THREAD

**Issue by xxcriticxx** [pascalopitz/unoffical-sonos-controller-for-linux#39]
i cant get pass NEXT button when trying to add service

**Comment by pascalopitz** [comment]
Any meaningful error in the console?

**Comment by MaxJonasG** [comment]
just this, which you should be able to reproduce as it never even asks for credentials
![screenshot from 2017-08-16 08-34-53](https://user-images.githubusercontent.com/25565941/29352399-77522a38-825e-11e7-956a-a5c0a727f3f8.png)

**Comment by ewagner70** [comment]
same here ... any chance to get a fix on apple music?
![image](https://user-images.githubusercontent.com/32803760/36397478-36a061f0-15c3-11e8-8e7a-186558e29512.png)

**Comment by pascalopitz** [comment]
So, I looked into this, and the answer is no. Apple Music Service needs some third party magic to work, which is not following the standard SMAPI specs, but also not disclosed anywhere. Shame.
