### ISSUE TITLE
add new music service

### ISSUE THREAD

**Issue by xxcriticxx** [pascalopitz/unoffical-sonos-controller-for-linux#4]
i install from deb file and when i click on add new music service nothing happens

i dont understand the part about install and run locally. where do i get node.js from?

**Comment by pascalopitz** [comment]
Hi there, could you do me a favour and check if there are any javascript errors?
Open the app, press ctrl+shift+i, to open the developer tools, then click the "Add new music service" bit and see if there's an error in the console?

**Comment by pascalopitz** [comment]
Okay, I verified the issue. Please re-download the latest .deb, remove the old app and re-install. Let me see how it goes. At this stage I only support Spotify and Soundcloud, as they're the only ones I have gotten to work so far :/.

**Comment by xxcriticxx** [comment]
@pascalopitz ubuntu 16.04 build 0.0.5

**Comment by xxcriticxx** [comment]
ok now i dont tink search works in music service

**Comment by pascalopitz** [comment]
Please check 0.0.6

**Comment by pascalopitz** [comment]
could you do me a favour and again check the console for any errors? thanks

**Comment by xxcriticxx** [comment]
i did already all works but search doesnt look like it works and i have 29 errors in the console dont know how to copy them here

**Comment by xxcriticxx** [comment]
![screenshot from 2016-12-04 21-00-06](https://cloud.githubusercontent.com/assets/15007183/20871538/d31c4ab4-ba64-11e6-9872-c60070c725ea.png)

**Comment by pascalopitz** [comment]
what service are you in, and what search are you running?

**Comment by xxcriticxx** [comment]
soundcloud skrillex

**Comment by pascalopitz** [comment]
Okay, download electron-0.0.7 and try again please

**Comment by xxcriticxx** [comment]
@pascalopitz after I get back from work I leave msg plus any errors here

**Comment by xxcriticxx** [comment]
i get first error when i go to soundcloud and then to new & hot then music pick gender for example popular music and i try to add 98 tracks to queue

rest of the errors is for when i add skrillex play list i guess some songs are not found. not all covers are found but thats small issue 

strange issue i see with this ver i see that from time to time the whole app blinks white now 

![screenshot from 2016-12-05 19-30-08](https://cloud.githubusercontent.com/assets/15007183/20908459/0a6e4cb0-bb23-11e6-8b7b-7b707b1e6ede.png)

**Comment by xxcriticxx** [comment]
i also cant figure out how to add music to the app. when i drop mp3 in the the app it just plays the song there is no way to go back to main app

**Comment by pascalopitz** [comment]
Ok we're muddling issues here ... I consider this fixed.

For now direct play from device to sonos is not supported. it's merely a controller for the music library accessible to sonos already and spotify/soundcloud. If you want to add more files, please connect NAS drive and index via offical app.

**Comment by xxcriticxx** [comment]
@pascalopitz nice job! i be back to test future versions
