### ISSUE TITLE
menu displays outside viewport when at bottom of app window.

### ISSUE THREAD

**Issue by xxcriticxx** [pascalopitz/unoffical-sonos-controller-for-linux#40]
Menues get cut off when you not in full screen mode

![img_6202](https://user-images.githubusercontent.com/15007183/29344551-b28adeb8-8206-11e7-959e-1b594c75b696.JPG)

**Comment by xxcriticxx** [comment]
more cut off menus in music library need arrow after gender

![screenshot from 2017-08-15 22-23-48](https://user-images.githubusercontent.com/15007183/29344853-b8ed7e6c-8208-11e7-8661-c59804cd7efb.png)

**Comment by pascalopitz** [comment]
This should be fixed as per v0.2.0-alpha2
