### ISSUE TITLE
Multiple ( Spotify ) Accounts, yet it appears to always picks the first when pressing play.

### ISSUE THREAD

**Issue by DraughtGlobe** [pascalopitz/unoffical-sonos-controller-for-linux#45]
I've registered my Spotify Account with the Unofficial Sonos Controller. Yet once i've set the playlist and it starts playing. It appears it will use the first Spotify account listed in the Sonos System itself.

Either allow the possibility for the selection of the Service Account for playback or try to find and use the Service Account that has been registered with the Unofficial Sonos Controller and use that one for playback.

**Comment by pascalopitz** [comment]
yes, the first account is always used at this stage. I'll look into it.

**Comment by pascalopitz** [comment]
I have found no good way to do this, and neither have others: https://github.com/bencevans/node-sonos/issues/350
