### ISSUE TITLE
Unable to play music since latest patch (8.2)

### ISSUE THREAD

**Issue by roggerooster** [pascalopitz/unoffical-sonos-controller-for-linux#48]
Unable to play music from eg. Spotify since latest patch. But music already in a queue is able to resume.

**Comment by roggerooster** [comment]
Thanks for the epic app btw. It is awesome!

**Comment by pascalopitz** [comment]
Is this still a problem? I cannot replicate it at all.

**Comment by pascalopitz** [comment]
The controller installed (8.2) should have nothing to do with this btw, as the ubuntu app bypasses it.

**Comment by roggerooster** [comment]
No I think the controller doesn't matter, but the issue turned up atleast for me after the patch. But the problem solved itself and everything works great since 3 days back. Might be an issue just for me :-(

**Comment by pascalopitz** [comment]
To follow this up: I had some problems with that, and subsequently updated the release v0.1.1, which fixes problems with householdId lookup and token refresh for SMAPI.

Please be aware to remove and re-add the services, as the household ID might not line up.
