### ISSUE TITLE
Playlist doesn't fully scroll down on long queues

### ISSUE THREAD

**Issue by PaulRauff** [pascalopitz/unoffical-sonos-controller-for-linux#49]
To reproduce: Queue up a hundred+ songs, then try and scroll to the end...

I haven't counted, but I don't think it gets past 50.

Possibly related: The playlist doesn't auto-scroll to the currently playing song.

(Thanks for a great app!)

**Comment by pascalopitz** [comment]
Can't reproduce this. Closing.
