### ISSUE TITLE
ports opened but still problems when firewall enabled

### ISSUE THREAD

**Issue by jkall** [pascalopitz/unoffical-sonos-controller-for-linux#5]
First of all: Great app! I can not understand there is no official linux controller for sonos. But your application is great.

I think I have encountered some issue related to the firewall. I have whitelisted ports as in the instructions but still have to disable the firewall (ufw) to le the controller contact sonos system. Thereafter I can enable the firewall again and use the controller fine for a period until it looses connection to my system. Then disabling firewall again fixes the connection instantly. 

Below you will find my ufw settings.

```
~$ sudo ufw status verbose

Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
1900:1901/udp              ALLOW IN    Anywhere
1400/tcp                   ALLOW IN    Anywhere
3400/tcp                   ALLOW IN    Anywhere
1900:1901/udp (v6)         ALLOW IN    Anywhere (v6)
1400/tcp (v6)              ALLOW IN    Anywhere (v6)
3400/tcp (v6)              ALLOW IN    Anywhere (v6)

```

**Comment by pascalopitz** [comment]
Hi, great find ...

> const SONOS_UPNP_RECEIVE_PORT = 1905;

Can you just whitelist that one and check if that helps?

**Comment by jkall** [comment]
OK, I tried that but no change.

```
~$ sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
1900:1901/udp              ALLOW IN    Anywhere
1400/tcp                   ALLOW IN    Anywhere
3400/tcp                   ALLOW IN    Anywhere
1905                       ALLOW IN    Anywhere
1905/tcp                   ALLOW IN    Anywhere
1905/udp                   ALLOW IN    Anywhere
1900:1901/udp (v6)         ALLOW IN    Anywhere (v6)
1400/tcp (v6)              ALLOW IN    Anywhere (v6)
3400/tcp (v6)              ALLOW IN    Anywhere (v6)
1905 (v6)                  ALLOW IN    Anywhere (v6)
1905/tcp (v6)              ALLOW IN    Anywhere (v6)
1905/udp (v6)              ALLOW IN    Anywhere (v6)

```

**Comment by pascalopitz** [comment]
Hmm, I'm a bit at a loss. Can you be a bit more specific what "looses connection to my system" exactly means? What kind of network setup do you run, do you change ip addresses frequently etc etc?

**Comment by pascalopitz** [comment]
Ok, should be better now as of [electron-0.0.8](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/download/electron-0.0.8/sonos-controller-unofficial-amd64.deb). 
Also updated the README to be more specific with the ports.
Please test and let me know?

**Comment by jkall** [comment]
Yes, now everything seems ok.  
I think you can close this now. 
Thank you!/J

**Comment by pascalopitz** [comment]
Great!
