### ISSUE TITLE
Not finding Sonos Speakers

### ISSUE THREAD

**Issue by guilhermemtr** [pascalopitz/unoffical-sonos-controller-for-linux#50]
Hi,

I hope it's not me who is messing up with this, but it appears that this controller is not finding my Sonos system. I noticed that I was getting the following error on the browser:
`this.socket.on('error', function(err) {
            self.emit('error', err);
        });`
Is there a way I can fix this? [I made sure I was in the correct wifi network].
Thank you in advance!

**Comment by programmin1** [comment]
On how many networks have you tested the SONOS speakers? Are you certain that devices are permitted to talk to each other through your router? Sometimes there is some network segmentation type option you may have to turn off in your router, sometimes it is some obscure bug like the one where you have to set "AES" instead of "TKIP+AES" on an Actiontec router...
https://superuser.com/questions/522781/unable-to-ssh-from-any-wireless-ip-to-another-wireless-ip-on-home-network/526515#526515

**Comment by guilhermemtr** [comment]
I've tested in two networks, and the speakers worked (and still work). The official SONOS app works (if this helps). And I am not aware of any bugs nor network segmentations that could cause this. All the speakers are connected to the same network, and when I test this I am also connected to the same network. How can I give more information about the error?

**Comment by km0001** [comment]
Installed on Mint 18.3. Checked for and installed graphicsMagick and icnsutils. 
When app starts the "Searching for your Sonos System ..." message is displayed and never goes away. I opened the developer console and noticed the following error being displayed:

`Uncaught TypeError: self.emit is not a function
    at Socket.<anonymous> (/opt/sonos-controller-unofficial/resources/app.asar/ui/sonos/Search.js:61:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at _handle.lookup (dgram.js:216:14)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)'

**Comment by guilhermemtr** [comment]
I changed from arch to mint 18.3, and I can also confirm that I have the problem (for the latest version available). Exactly the same as km0001 mentioned.

**Comment by pascalopitz** [comment]
Ok, two things going on here:
- Search is not an emitter, so the stack trace is produced, instead of telling the error properly.
- Maybe a port conflict? Ports 1900 and 1905 need to be accessible and not taken by other resources.

I'll make the error logging more verbose.

**Comment by iisquazar** [comment]
I'm also affected by this bug. Same  error as km0001.
Not sure if nmp is installed correctly on my Ubuntu system though.

`npm run develop
npm ERR! Linux 4.13.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "develop"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! path /home/username/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/username/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/username/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/npm-debug.log
`

**Comment by darioce** [comment]
I had the same issue as km0001. I checked my firewall settings and there was nothing suspicious. However, as soon as I turned off the firewall, everything was fine. So I allowed the two ports 1905/1900 on both protocols and both directions and the problem was INSTANTLY resolved.
I don't know why they were blocked in the first place...

**Comment by tomchiverton** [comment]
Works fine. Close as not-a-bug ?

**Comment by john-parker** [comment]
![image](https://user-images.githubusercontent.com/10309350/48722620-73126b00-ebf2-11e8-9a58-ed730f591866.png)
I love this program but it has stopped working on my Ubuntu 18.04,1LTS machines. I get the "Searching for your Sonos System ..." message. I tried opening ports 1900 and 1905 via "sudo ufw allow 190x" (see attached screenshot). Can I provide any developer tools output that might help diagnose the bug? 
![selection_179](https://user-images.githubusercontent.com/10309350/48722934-4dd22c80-ebf3-11e8-8e2b-98de08ff6c86.png)

**Comment by pascalopitz** [comment]
Gonna close this.
