### ISSUE TITLE
Drag and drop doesn't work... unclear how to add songs.

### ISSUE THREAD

**Issue by programmin1** [pascalopitz/unoffical-sonos-controller-for-linux#51]
When I drag and drop a song onto it it makes the entire app go away and there's just a play button audio player, and it plays _on the computer_!

Very frustration to not have an obvious way to add music and hitting the ... button next to Queue apparently makes all music go away? Why??

**Comment by pascalopitz** [comment]
Clear all clears queue. Local files is a different ticket.
