### ISSUE TITLE
Radio playlist also do next on local playlist

### ISSUE THREAD

**Issue by joyarzun** [pascalopitz/unoffical-sonos-controller-for-linux#53]
When you are playing a Radio playlist, you press next and change to next song, but also change to next song on your local playlist (just marked it active). For example, the first screenshot is my current state. Then, I press next song and you have the second screenshot. You can see that on my local playlist is selected the next song but I playing a radio, so it's a little bug.

![selection_008](https://user-images.githubusercontent.com/828211/34440559-aa181068-ec94-11e7-90ea-1a7bb4171dc1.png)

![selection_009](https://user-images.githubusercontent.com/828211/34440566-b0c3137c-ec94-11e7-8ba3-c5835459164d.png)

**Comment by pascalopitz** [comment]
So the control should be blocked or hidden?
How do you play a radio playlist? What service do you use?

**Comment by joyarzun** [comment]
I think the control should be blocked or even better the event "mark next song" should not be triggered. I play radio on Google Play Music

**Comment by pascalopitz** [comment]
I cannot replicate this. Is this still an issue?

**Comment by joyarzun** [comment]
> I cannot replicate this. Is this still an issue?

I don't know. This happened a long time ago. Now I'm running on mac, so maybe I should close this
