### ISSUE TITLE
Tidal music service - nothing happening when hitting 'next'

### ISSUE THREAD

**Issue by dagbdagb** [pascalopitz/unoffical-sonos-controller-for-linux#54]
Hi. Thank you for making this.

Wen I try to add my Tidal subscription, I get the regular disclaimer about experimental support and so on.
However, when I hit 'next', nothing happens. Is this expected?

What can I do to improve the chances of this app supporting Tidal?

Thanks,

Dag B

**Comment by ericduran** [comment]
Having the same issue with Tidal, It throws an XML Error:
 ```
<!DOCTYPE html>
<html lang="en">
 ..........
    <body>
        <h1>Bad Request</h1>
        <p id="detail">
            For request 'POST /v1/sonos' [Invalid XML: Invalid encoding name &quot;UTF8&quot;.]
        </p>
    </body>
</html>
    at parseXML (/opt/sonos-controller-unofficial/resources/app.asar/node_modules/jquery-xml2json/src/xml2json.js:35)
```

**Comment by pascalopitz** [comment]
So, I re-checked this and initiate the signup page, but then Tidal throws an error somehow during the process for me. Maybe because of my geo-location. Can someone else try again please?

**Comment by pascalopitz** [comment]
SAme on the android app. ![Screenshot_20200617-093724](https://user-images.githubusercontent.com/271740/84840277-392f7200-b07e-11ea-9f07-c8434bd8d181.png)

**Comment by pascalopitz** [comment]
Ok, solved. I had to complete the onboarding flow in the tidal web app, before it allowed me to add to sonos. After that it worked as expected.
