### ISSUE TITLE
plex integration

### ISSUE THREAD

**Issue by goosmaster** [pascalopitz/unoffical-sonos-controller-for-linux#56]
Running Ubuntu 16.04 with Gnome
Unofficial Sonos Controller version 0.1.2

I connected my plex account successfully to the client, but once I select the plex music service, I get an empty list. When I look into the developer console, it generates the following error:

```
TypeError: Cannot create property 'serviceClient' on string 'PMS|:PMS/7c62c345691ea62fefd87f491dc5d21b:NONE#cw0v'
    at state.items._lodash2.default.map.i (BrowserListActions.js:373)
    at /opt/sonos-controller-unofficial/resources/app.asar/node_modules/lodash/lodash.js:3554
    at /opt/sonos-controller-unofficial/resources/app.asar/node_modules/lodash/lodash.js:4944
    at baseForOwn (/opt/sonos-controller-unofficial/resources/app.asar/node_modules/lodash/lodash.js:3001)
    at /opt/sonos-controller-unofficial/resources/app.asar/node_modules/lodash/lodash.js:4913
    at baseMap (/opt/sonos-controller-unofficial/resources/app.asar/node_modules/lodash/lodash.js:3553)
    at Function.map (/opt/sonos-controller-unofficial/resources/app.asar/node_modules/lodash/lodash.js:9571)
    at exports.select (BrowserListActions.js:372)
    at <anonymous>
action.payload.action.payload.catch.err @ index.js:30
```

**Comment by pascalopitz** [comment]
AFAIK Pandora is some special hardcoded music service and has magic IDs etc, as it was the first thing Sonos shipped with. Since they removed it all together for Australia, I have no way to even get started on reverse-engineering ... If someone has a pull request to make it work I'll happily merge.

**Comment by pascalopitz** [comment]
@goosmaster still a problem?

**Comment by pascalopitz** [comment]
Ok, just checked. Works for me.
