### ISSUE TITLE
Grouping/Ungrouping zones responds slowly and jumps back and forth between states

### ISSUE THREAD

**Issue by KilianB** [pascalopitz/unoffical-sonos-controller-for-linux#57]
When grouping multiple rooms and ungrouping those again later on, to transfer zones, the room ui section might beceome non responsive. I also observed that after ungrouping the ui updates a few times showing the rooms grouped again.

**Comment by pascalopitz** [comment]
yes, this is a problem, which i also have observed with the Android app, to be fair. The model here is that I tell it how to group, then the updates come through via UPNP Event notifications. Not sure there is a better way? The workaround I implemented is a few delayed state polls to update the UI quicker.

**Comment by pascalopitz** [comment]
I'm going to close this. v0.2.0-alpha2 should have brought in a change to this. It's still relying on notifications but overall it seems to be snappier.
