### ISSUE TITLE
Can I use line-in

### ISSUE THREAD

**Issue by Xerus2000** [pascalopitz/unoffical-sonos-controller-for-linux#58]
What's up with line-in? Is it supposed to stream local sound? I would appreciate a guide on how to use this

**Comment by pascalopitz** [comment]
https://sonos.custhelp.com/app/answers/detail/a_id/1091/~/using-line-in-on-sonos

**Comment by Xerus2000** [comment]
Oh ok. Ended up using pulseaudio-dlna ^^
