### ISSUE TITLE
can't see sources

### ISSUE THREAD

**Issue by michiil** [pascalopitz/unoffical-sonos-controller-for-linux#6]
Hey there,
I just tried your app (via npm) on a raspberry pi.
It seems to work pretty well, the only problem is: i can't see my music services.
When I click on Add New Music Services, only Soundcloud is aviable.

Here is a screenhot from the console erros:
![selection_002](https://cloud.githubusercontent.com/assets/5451489/21010403/304e0530-bd4c-11e6-97ab-14224ee02e76.png)

Do you have any idea why this happens?

Thanks in advance

**Comment by xxcriticxx** [comment]
@michiil only soundclound and spotify premium available right now

**Comment by pascalopitz** [comment]
As for now that's correct. If you have a particular music service in mind we could try and figure out how to make that work. Google Play I've tried and failed, others might be possible as long as they properly follow the smapi specification.

**Comment by xxcriticxx** [comment]
@pascalopitz can you try slacker and amazon?

**Comment by michiil** [comment]
For me it would be subsonic.
If you want to try it and need some more information i can help of course!

**Comment by pascalopitz** [comment]
Subsonic doesn't even come up in my service list.

`[
    {
        "Id": "221",
        "Name": "LivePhish+",
        "Version": "1.1",
        "Uri": "https://sonos.nugs.net/soap/livephish",
        "SecureUri": "https://sonos.nugs.net/soap/livephish",
        "ContainerType": "SoundLab",
        "Capabilities": "6675",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 56583
    },
    {
        "Id": "192",
        "Name": "focus@will",
        "Version": "1.1",
        "Uri": "https://www.focusatwill.com/sonos/action",
        "SecureUri": "https://www.focusatwill.com/sonos/action",
        "ContainerType": "MService",
        "Capabilities": "5632",
        "Auth": "UserId",
        "PollInterval": "3600",
        "ServiceIDEncoded": 49159
    },
    {
        "Id": "222",
        "Name": "nugs.net",
        "Version": "1.1",
        "Uri": "https://sonos.nugs.net/soap/nugs",
        "SecureUri": "https://sonos.nugs.net/soap/nugs",
        "ContainerType": "SoundLab",
        "Capabilities": "6675",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 56839
    },
    {
        "Id": "201",
        "Name": "Amazon Music",
        "Version": "1.1",
        "Uri": "https://sonos.amazonmusic.com/",
        "SecureUri": "https://sonos.amazonmusic.com/",
        "ContainerType": "MService",
        "Capabilities": "45633",
        "Auth": "DeviceLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 51463
    },
    {
        "Id": "37",
        "Name": "SiriusXM",
        "Version": "1.1",
        "Uri": "http://siriusxm.ws.sonos.com/smapi",
        "SecureUri": "https://siriusxm.ws.sonos.com/smapi",
        "ContainerType": "MService",
        "Capabilities": "0",
        "Auth": "UserId",
        "PollInterval": "1800",
        "ServiceIDEncoded": 9479
    },
    {
        "Id": "12",
        "Name": "Spotify",
        "Version": "1.1",
        "Uri": "https://spotify-v4.ws.sonos.com/smapi",
        "SecureUri": "https://spotify-v4.ws.sonos.com/smapi",
        "ContainerType": "MService",
        "Capabilities": "1116691",
        "Auth": "AppLink",
        "PollInterval": "300",
        "ServiceIDEncoded": 3079
    },
    {
        "Id": "168",
        "Name": "Deezer",
        "Version": "1.1",
        "Uri": "http://api.deezer.com/sonos",
        "SecureUri": "https://api.deezer.com/sonos",
        "ContainerType": "MService",
        "Capabilities": "6739",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 43015
    },
    {
        "Id": "219",
        "Name": "Audiobooks.com",
        "Version": "1.1",
        "Uri": "https://api.audiobooks.com/api/v2/sonos/soap",
        "SecureUri": "https://api.audiobooks.com/api/v2/sonos/soap",
        "ContainerType": "MService",
        "Capabilities": "4672",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 56071
    },
    {
        "Id": "202",
        "Name": "Napster",
        "Version": "1.1",
        "Uri": "http://sonosapi-napster-ns.rhapsody.com/smapi",
        "SecureUri": "https://sonosapi-napster.rhapsody.com/smapi",
        "ContainerType": "MService",
        "Capabilities": "595",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 51719
    },
    {
        "Id": "160",
        "Name": "SoundCloud",
        "Version": "1.1",
        "Uri": "https://soundcloud-go.ws.sonos.com/smapi",
        "SecureUri": "https://soundcloud-go.ws.sonos.com/smapi",
        "ContainerType": "MService",
        "Capabilities": "4611",
        "Auth": "DeviceLink",
        "PollInterval": "30",
        "ServiceIDEncoded": 40967
    },
    {
        "Id": "33",
        "Name": "Murfie",
        "Version": "1.1",
        "Uri": "http://sonos.murfie.com/",
        "SecureUri": "https://sonos.murfie.com/",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 8455
    },
    {
        "Id": "184",
        "Name": "Stingray Music",
        "Version": "1.1",
        "Uri": "http://sonos.stingray.com/ws/Sonos",
        "SecureUri": "https://sonos.stingray.com/ws/Sonos",
        "ContainerType": "MService",
        "Capabilities": "295427",
        "Auth": "DeviceLink",
        "PollInterval": "600",
        "ServiceIDEncoded": 47111
    },
    {
        "Id": "174",
        "Name": "TIDAL",
        "Version": "1.1",
        "Uri": "http://sonos.tidalhifi.com/sonos",
        "SecureUri": "https://sonos.tidalhifi.com/sonos",
        "ContainerType": "MService",
        "Capabilities": "2579",
        "Auth": "UserId",
        "PollInterval": "120",
        "ServiceIDEncoded": 44551
    },
    {
        "Id": "159",
        "Name": "Groove",
        "Version": "1.1",
        "Uri": "https://sonos.music.microsoft.com/api",
        "SecureUri": "https://sonos.auth.music.microsoft.com/api",
        "ContainerType": "MService",
        "Capabilities": "35347",
        "Auth": "DeviceLink",
        "PollInterval": "300",
        "ServiceIDEncoded": 40711
    },
    {
        "Id": "217",
        "Name": "FIT Radio Workout Music",
        "Version": "1.1",
        "Uri": "http://www.fitradio.com/apisonos/ws",
        "SecureUri": "https://www.fitradio.com/apisonos/ws",
        "ContainerType": "MService",
        "Capabilities": "4610",
        "Auth": "DeviceLink",
        "PollInterval": "120",
        "ServiceIDEncoded": 55559
    },
    {
        "Id": "162",
        "Name": "radioPup",
        "Version": "1.1",
        "Uri": "http://sonos.townsquaremedia.com/index.php",
        "SecureUri": "https://sonos.townsquaremedia.com/index.php",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "Anonymous",
        "PollInterval": "3600",
        "ServiceIDEncoded": 41479
    },
    {
        "Id": "181",
        "Name": "Mixcloud",
        "Version": "1.1",
        "Uri": "https://www.mixcloud.com/sonos-app/",
        "SecureUri": "https://www.mixcloud.com/sonos-app/",
        "ContainerType": "MService",
        "Capabilities": "2627",
        "Auth": "DeviceLink",
        "PollInterval": "30",
        "ServiceIDEncoded": 46343
    },
    {
        "Id": "6",
        "Name": "iHeartRadio",
        "Version": "1.1",
        "Uri": "http://sonos.iheart.com/soap",
        "SecureUri": "https://sonos.iheart.com/soap",
        "ContainerType": "MService",
        "Capabilities": "4673",
        "Auth": "DeviceLink",
        "PollInterval": "3600",
        "ServiceIDEncoded": 1543
    },
    {
        "Id": "44",
        "Name": "Hype Machine",
        "Version": "1.1",
        "Uri": "http://api.hypem.com/api/sonos",
        "SecureUri": "https://api.hypem.com/api/sonos",
        "ContainerType": "MService",
        "Capabilities": "577",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 11271
    },
    {
        "Id": "38",
        "Name": "7digital",
        "Version": "1.1",
        "Uri": "http://sonos-service.7digital.com/sonos.asmx",
        "SecureUri": "https://sonos-service.7digital.com/sonos.asmx",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 9735
    },
    {
        "Id": "204",
        "Name": "Apple Music",
        "Version": "1.1",
        "Uri": "https://sonos-music.apple.com/ws/SonosSoap",
        "SecureUri": "https://sonos-music.apple.com/ws/SonosSoap",
        "ContainerType": "MService",
        "Capabilities": "1020481",
        "Auth": "AppLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 52231
    },
    {
        "Id": "198",
        "Name": "Anghami",
        "Version": "1.1",
        "Uri": "https://api.anghami.com/anghmob/SonosAPI.php",
        "SecureUri": "https://api.anghami.com/anghmob/SonosAPI.php",
        "ContainerType": "MService",
        "Capabilities": "2627",
        "Auth": "DeviceLink",
        "PollInterval": "90",
        "ServiceIDEncoded": 50695
    },
    {
        "Id": "189",
        "Name": "SOUNDMACHINE",
        "Version": "1.1",
        "Uri": "http://provider.sound-machine.com/sonosapi",
        "SecureUri": "https://provider.sound-machine.com/sonosapi",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "UserId",
        "PollInterval": "120",
        "ServiceIDEncoded": 48391
    },
    {
        "Id": "213",
        "Name": "Custom Channels",
        "Version": "1.1",
        "Uri": "http://ensemble.customchannels.net/sonos",
        "SecureUri": "https://ensemble.customchannels.net/sonos",
        "ContainerType": "MService",
        "Capabilities": "8704",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 54535
    },
    {
        "Id": "212",
        "Name": "Plex",
        "Version": "1.1",
        "Uri": "https://sonos.plex.tv/sonos/",
        "SecureUri": "https://sonos.plex.tv/sonos/",
        "ContainerType": "SoundLab",
        "Capabilities": "513",
        "Auth": "DeviceLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 54279
    },
    {
        "Id": "186",
        "Name": "Dash Radio",
        "Version": "1.1",
        "Uri": "http://54.191.183.105/sonos/MusicBrainzPHP/SonosAPI.php",
        "SecureUri": "http://54.191.183.105/sonos/MusicBrainzPHP/SonosAPI.php",
        "ContainerType": "MService",
        "Capabilities": "512",
        "Auth": "DeviceLink",
        "PollInterval": "30",
        "ServiceIDEncoded": 47623
    },
    {
        "Id": "151",
        "Name": "Google Play Music",
        "Version": "1.1",
        "Uri": "https://mclients.googleapis.com/music/sonos/wsf/smapi",
        "SecureUri": "https://mclients.googleapis.com/music/sonos/wsf/smapi",
        "ContainerType": "MService",
        "Capabilities": "98899",
        "Auth": "DeviceLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 38663
    },
    {
        "Id": "210",
        "Name": "Rockbot",
        "Version": "1.1",
        "Uri": "http://api.rockbot.com/v2/sonos",
        "SecureUri": "https://api.rockbot.com/v2/sonos",
        "ContainerType": "MService",
        "Capabilities": "45632",
        "Auth": "DeviceLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 53767
    },
    {
        "Id": "187",
        "Name": "NhacCuaTui",
        "Version": "1.1",
        "Uri": "https://sonos.nhaccuatui.com/sonos/api",
        "SecureUri": "https://sonos.nhaccuatui.com/sonos/api",
        "ContainerType": "SoundLab",
        "Capabilities": "33345",
        "Auth": "DeviceLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 47879
    },
    {
        "Id": "169",
        "Name": "Tribe of Noise",
        "Version": "1.1",
        "Uri": "http://sonos.tribeofnoise.com/server-v2.0.php",
        "SecureUri": "https://sonos.tribeofnoise.com/server-v2.0.php",
        "ContainerType": "MService",
        "Capabilities": "512",
        "Auth": "DeviceLink",
        "PollInterval": "3600",
        "ServiceIDEncoded": 43271
    },
    {
        "Id": "17",
        "Name": "Slacker",
        "Version": "1.1",
        "Uri": "http://sonos.slacker.com/wsv1/sonos",
        "SecureUri": "https://sonos.slacker.com/wsv1/sonos",
        "ContainerType": "MService",
        "Capabilities": "2643",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 4359
    },
    {
        "Id": "171",
        "Name": "Mood Mix",
        "Version": "1.1",
        "Uri": "http://sonos.mix.moodmedia.com/api",
        "SecureUri": "https://sonos.mix.moodmedia.com/api",
        "ContainerType": "MService",
        "Capabilities": "4609",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 43783
    },
    {
        "Id": "191",
        "Name": "Classical Archives",
        "Version": "1.1",
        "Uri": "https://api.classicalarchives.com/smapi/endpoint",
        "SecureUri": "https://api.classicalarchives.com/smapi/endpoint",
        "ContainerType": "MService",
        "Capabilities": "1030739",
        "Auth": "DeviceLink",
        "PollInterval": "600",
        "ServiceIDEncoded": 48903
    },
    {
        "Id": "42",
        "Name": "Batanga",
        "Version": "1.1",
        "Uri": "http://sonos.batanga.com/batanga.asmx",
        "SecureUri": "https://sonos.batanga.com:4343/batanga.asmx",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 10759
    },
    {
        "Id": "188",
        "Name": "AccuRadio",
        "Version": "1.1",
        "Uri": "http://www.accuradio.com/arsonos/",
        "SecureUri": "https://www.accuradio.com/arsonos/",
        "ContainerType": "MService",
        "Capabilities": "34369",
        "Auth": "DeviceLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 48135
    },
    {
        "Id": "146",
        "Name": "Daytrotter",
        "Version": "1.1",
        "Uri": "http://www.daytrotter.com/ws/MOAPI.asmx",
        "SecureUri": "https://www.daytrotter.com/ws/MOAPI.asmx",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "UserId",
        "PollInterval": "600",
        "ServiceIDEncoded": 37383
    },
    {
        "Id": "7",
        "Name": "Concert Vault",
        "Version": "1.1",
        "Uri": "http://www.concertvault.com/ws/MOAPI.asmx",
        "SecureUri": "https://www.concertvault.com/ws/MOAPI.asmx",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 1799
    },
    {
        "Id": "167",
        "Name": "Gaana",
        "Version": "1.1",
        "Uri": "http://sonosapi.gaana.com/SonosAPI.php",
        "SecureUri": "http://sonosapi.gaana.com/SonosAPI.php",
        "ContainerType": "MService",
        "Capabilities": "577",
        "Auth": "DeviceLink",
        "PollInterval": "200",
        "ServiceIDEncoded": 42759
    },
    {
        "Id": "164",
        "Name": "Saavn",
        "Version": "1.1",
        "Uri": "http://www.saavn.com/apps/sonos/SonosAPI.php",
        "SecureUri": "https://www.saavn.com/apps/sonos/SonosAPI.php",
        "ContainerType": "MService",
        "Capabilities": "12865",
        "Auth": "DeviceLink",
        "PollInterval": "120",
        "ServiceIDEncoded": 41991
    },
    {
        "Id": "163",
        "Name": "Spreaker",
        "Version": "1.1",
        "Uri": "http://sonos.spreaker.com/sonos/service/v1",
        "SecureUri": "https://sonos.spreaker.com/sonos/service/v1",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "Anonymous",
        "PollInterval": "30",
        "ServiceIDEncoded": 41735
    },
    {
        "Id": "157",
        "Name": "Bandcamp",
        "Version": "1.1",
        "Uri": "http://sns.bandcamp.com/api/sonos/2/sonos_api",
        "SecureUri": "https://sns.bandcamp.com/api/sonos/2/sonos_api",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "DeviceLink",
        "PollInterval": "60",
        "ServiceIDEncoded": 40199
    },
    {
        "Id": "154",
        "Name": "Radionomy",
        "Version": "1.1",
        "Uri": "http://sonos.radionomy.com/SonosService.svc",
        "SecureUri": "https://sonos.radionomy.com/SonosService.svc",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 39431
    },
    {
        "Id": "150",
        "Name": "RUSC",
        "Version": "1.1",
        "Uri": "http://www.rusc.com/sonos.asmx",
        "SecureUri": "https://www.rusc.com/sonos.asmx",
        "ContainerType": "MService",
        "Capabilities": "512",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 38407
    },
    {
        "Id": "144",
        "Name": "Calm Radio",
        "Version": "1.1",
        "Uri": "https://api.calmradio.com/sonos/",
        "SecureUri": "https://api.calmradio.com/sonos/",
        "ContainerType": "MService",
        "Capabilities": "512",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 36871
    },
    {
        "Id": "53",
        "Name": "MLB.com Gameday Audio",
        "Version": "1.1",
        "Uri": "https://securea.mlb.com/ce/sonos/default.jsp",
        "SecureUri": "https://securea.mlb.com/ce/sonos/default.jsp",
        "ContainerType": "MService",
        "Capabilities": "1536",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 13575
    },
    {
        "Id": "45",
        "Name": "hotelradio.fm",
        "Version": "1.1",
        "Uri": "http://users.hotelradio.fm/sonosapi/index.php",
        "SecureUri": "https://users.hotelradio.fm/sonosapi/index.php",
        "ContainerType": "MService",
        "Capabilities": "512",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 11527
    },
    {
        "Id": "36",
        "Name": "Hearts of Space",
        "Version": "1.1",
        "Uri": "http://sonos.hos.com/SOAP/Server1.2.php",
        "SecureUri": "https://sonos.hos.com/SOAP/Server1.2.php",
        "ContainerType": "MService",
        "Capabilities": "512",
        "Auth": "UserId",
        "PollInterval": "1200",
        "ServiceIDEncoded": 9223
    },
    {
        "Id": "24",
        "Name": "DAR.fm Record Radio",
        "Version": "1.1",
        "Uri": "http://dar.fm/SonosServer.php",
        "SecureUri": "http://dar.fm/SonosServer.php",
        "ContainerType": "MService",
        "Capabilities": "512",
        "Auth": "UserId",
        "PollInterval": "30",
        "ServiceIDEncoded": 6151
    },
    {
        "Id": "13",
        "Name": "Stitcher SmartRadio",
        "Version": "1.1",
        "Uri": "http://www.stitcher.com/Service/Sonos/Sonos.php",
        "SecureUri": "https://www.stitcher.com/Service/Sonos/Sonos.php",
        "ContainerType": "MService",
        "Capabilities": "579",
        "Auth": "UserId",
        "PollInterval": "60",
        "ServiceIDEncoded": 3335
    },
    {
        "Id": "240",
        "Name": "Jamendo 240",
        "Version": "1.1",
        "Uri": "http://192.168.10.13:8888/soap",
        "SecureUri": "http://192.168.10.13:8888/soap",
        "ContainerType": "MService",
        "Capabilities": "1",
        "Auth": "Anonymous",
        "PollInterval": "300",
        "ServiceIDEncoded": 61447
    },
    {
        "Id": "241",
        "Name": "jamendo 241",
        "Version": "1.1",
        "Uri": "http://jamendo.pascalopitz.com/soap",
        "SecureUri": "http://jamendo.pascalopitz.com/soap",
        "ContainerType": "MService",
        "Capabilities": "513",
        "Auth": "Anonymous",
        "PollInterval": "900",
        "ServiceIDEncoded": 61703
    },
    {
        "Id": "252",
        "Name": "Guvera @ 252",
        "Version": "1.1",
        "Uri": "http://192.168.10.2:8080/soap",
        "SecureUri": "https://192.168.10.2:10443/soap",
        "ContainerType": "MService",
        "Capabilities": "1",
        "Auth": "UserId",
        "PollInterval": "500",
        "ServiceIDEncoded": 64519
    },
    {
        "Id": "253",
        "Name": "mysoundcloud",
        "Version": "1.1",
        "Uri": "http://mysoundcloud.ap01.aws.af.cm/SoapService",
        "SecureUri": "https://mysoundcloud.ap01.aws.af.cm/SoapService",
        "ContainerType": "MService",
        "Capabilities": "563",
        "Auth": "UserId",
        "PollInterval": "0",
        "ServiceIDEncoded": 64775
    }
]"`

**Comment by pascalopitz** [comment]
Ok, I made a pre-release with probably some really glitchy stuff in it. Whitelisted all UserID reeleases that use session based auth in smapi.

https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/download/v0.0.9-alpha1/sonos-controller-unofficial-amd64.deb

Please test and give feedback, but keep in mind that I 

a) won't sign up for paid services unless reimbursed
b) Might not get the same services due to device and region capabilities
c) Only dogfooding I do is Soundcloud and Spotify

Have fun

**Comment by xxcriticxx** [comment]
@pascalopitz can we install 2 different version on the same time?

**Comment by pascalopitz** [comment]
no idea, haven't tried. You can just clone the project, do an `npm install` and run it via `npm run develop` though

**Comment by michiil** [comment]
Subsonic is a local music server, so it only shows up when you install it (:
Subsonic now shows up under 'Add New Music Services', but it's not there in select a music source..

**Comment by michiil** [comment]
Okay after adding it a second time throu your app it shows up and works (:
Thanks a lot!
