### ISSUE TITLE
Snap install warning

### ISSUE THREAD

**Issue by davidmn** [pascalopitz/unoffical-sonos-controller-for-linux#60]
When installing the snap I get the following error:
```
error: cannot find signatures with metadata for snap "sonos-controller-unofficial_0.1.3_amd64.snap"

```

When I run `snap ack` on the snap I get the following:
```
error: cannot assert: cannot decode request body into assertions: parsing assertion headers: header is not utf8

```

System info is:
```
snap    2.32.5+18.04
snapd   2.32.5+18.04
series  16
ubuntu  18.04
kernel  4.15.0-20-generic
```

**Comment by pascalopitz** [comment]
So this is an incorrectly signed snap? Does it still install /  run?

**Comment by davidmn** [comment]
If you pass the `--dangerous` arguement it installs and works.

**Comment by pascalopitz** [comment]
So, the snaps are generated by electron-builder ... not sure what went wrong there?

**Comment by davidmn** [comment]
I've looked into this and I think it fails because snap cannot assert the snap. Which from [here](https://github.com/snapcore/snapd/wiki/Assertions) suggests that it checks if the downloaded snap is from the snap repositories. We could publish the snap in the snap store so people could install it without downloading the snap file from the github release page.

**Comment by pascalopitz** [comment]
fwiw i removed snap ... a) because of the warning, b) because it messes up arm builds and c) because of the ridiculous file size of the artefact
