### ISSUE TITLE
Support for "additional" net interface

### ISSUE THREAD

**Issue by oxivanisher** [pascalopitz/unoffical-sonos-controller-for-linux#62]
I am responsible for the IT of a small Hotel and got "surprised" by them with buying Sonos. Since the IT is completely realized with Debian/Ubuntu I would love to use your application. But I found a limitation, which would be great if it could be worked around.

Since Sonos is not supporting WPA Enterprise*, I had to put them into the VOIP Wifi and then do a "hack" by adding a additional Vlan to the Ubuntu PC which should control the Sonos system. If the default gateway points to the VOIP-Vlan, it finds the Sonos system without any problems (but everything using Internet is not working, so no solution there...). But if the gateway points to the LAN, the Sonos system is not discovered.

Is there a possibility to specify a interface on which to work on for the Sonos controller? Since Sonos works with Multicast, specifying a IP range will not help.

* routing Multicast between networks is also not working, I tried for hours and Sonos is offering no help on this

**Comment by pascalopitz** [comment]
Maybe you need to re-jig the network and use the Android/iOS app by directly connecting to the mesh network?
