### ISSUE TITLE
Amazon Prime Music

### ISSUE THREAD

**Issue by ZEROF** [pascalopitz/unoffical-sonos-controller-for-linux#63]
Hi,

Connect to Amazon Prime Music account is working, but I can't plat any of titres or play-list. Like daily play-list etc.

Thanks

**Comment by GospelNerd** [comment]
Also seeing this. I was able to add the account, but when I try to play anything, the request to "/MediaRenderer/AVTransport/Control" responds with a 500 error. The response body shows a UPnP error code 800:
`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>800</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>`

**Comment by pascalopitz** [comment]
I don't have a subscription for it, and I am not even sure it comes up here in Australia ... in any case, I won't be able to help out with it.

**Comment by pascalopitz** [comment]
Of course, if there's a good pull request I'll be happy to merge that.

**Comment by stan-qaz** [comment]
This is a bit old a bug but I have some more information to add that may help.

If I select Amazon and a track I can't get "Play" to work but it will add to the queue and play from there. Attached is my app state file (.txt added to allow upload)

Any further testing I can do or info I can provide I will be happy to send along.

[Amazon-Music-unoffical-sonos-controller.appState.json.txt](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4741573/Amazon-Music-unoffical-sonos-controller.appState.json.txt)

**Comment by pascalopitz** [comment]
Yes. I has similar behaviour yesterday when trying to "play now" a spotify track while a radio stream was running. Will look into it. Does the developer console show any stack traces?

**Comment by stan-qaz** [comment]
Appears to have been fixed in Beta 6, Play Now, Next, Add and Replace all are working now.

**Comment by pascalopitz** [comment]
Which is odd, because from beta5 to beta6 there was no specific code change to address that ...

**Comment by stan-qaz** [comment]
That is odd, I moved Beta 5 to the recycle bin, downloaded 6, set it to executable and when opened things were working. With Beta 5 I'd tried it, rebooted and tried again it still didn't work. 

I'm on a Pi 3B+ if that might matter.

**Comment by pascalopitz** [comment]
I [changed the way play now works](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/commit/9c013d52f439b22eea160d05254c3debca53f75d#diff-f7dc1af111b63e434ce3396e3617948aR512). It should work better.

**Comment by pascalopitz** [comment]
@stan-qaz Has my change worked for you? Can I close this issue?

**Comment by stan-qaz** [comment]
It is working well, please close this.
