### ISSUE TITLE
New update Sonos; Controller for linux keeps searching for sonos

### ISSUE THREAD

**Issue by wtrz** [pascalopitz/unoffical-sonos-controller-for-linux#64]
Today received sonos update 9.1 (build 45156150).

Official Sonos controller (android) works
Unofficial Sonos controller for linux keeps searching for sonos system. 
![screenshot](https://user-images.githubusercontent.com/14895091/45171636-2f1ee500-b203-11e8-9569-2446e65df84b.png)

**Comment by ericmo1** [comment]
Hello, i'm facing the same issue...
Only installed the controller yesterday for the first time (this was holding me back to step away from windows)
Snap install went fine on Xubuntu 18.04, but then i got the same message as above.
Hopefully you can find a fix.

Thanks in advace

**Comment by DatStorm** [comment]
Same here.

Am on Ubuntu 18.04 on cable (not wifi). But should not be an issue.

**Comment by harobert1** [comment]
After updateing Sonos to 9.1 Unofficial Sonos controller does not work anymore.
(Linux Mint 18.3)

**Comment by pascalopitz** [comment]
Yep, confirmed ... see https://github.com/bencevans/node-sonos/issues/332

I am working on a fix, but it won't be today.
The way to do this is using the ZoneGroupTopology service instead of the undocumented xml previously exposed.

**Comment by pascalopitz** [comment]
v0.1.5 just pushed ... which should fix that

**Comment by pascalopitz** [comment]
Can everyone check this is fixed in v0.1.5 release?

**Comment by harobert1** [comment]
Dear Pascal,
I tested, it works fine.
Thank you very much!
harobert1

**Comment by wtrz** [comment]
I can confirm 'Unofficial Sonos controller for linux' is working after upgrading to release 0.1.5.

**Comment by marrs** [comment]
I installed this version today on PureOS, which is a derivative of Debian testing, and I'm seeing the same loading screen
