### ISSUE TITLE
Arch AUR Support

### ISSUE THREAD

**Issue by PaddyPad** [pascalopitz/unoffical-sonos-controller-for-linux#68]
Hi, is there any chance you can push this to the AUR so I can use this in Arch/Antergos Linux. I have been looking for a descent Sonos App for Linux for a long time.

**Comment by R8s6** [comment]
Alternatively, could you (@PaddyPad ) please share how to build it from source (for any distro), such as putting it into README.md? 

With that, I think it'll be a lot easier to bring it to Arch AUR.

Thanks!

**Comment by PaddyPad** [comment]
@R8s6 thanks for the quick answer. So far I haven't figured out how to build it from source. Converting the .deb package to a package that pacman can use hasn't worked to my satisfaction either so far(dropbox, etcher and icecat are being installed as dependencies on the side, as soon as in uninstall one of them again, sonos-controller-unofficial is uninstalled alongside with it). When I figure out how to build a pacman package or how to build it from source, I'll post it here.
Thanks

**Comment by pascalopitz** [comment]
Ok, so travis does this:

`- npm run fonts
- npm run transpile
- npm run dist`

Where the last step is:

`build --x64 --armv7`


What you can do isntead is:

`npm run pack`

and that will generate a distribution directory unpacked. Does that help?

More here: https://www.electron.build/

**Comment by pascalopitz** [comment]
Oh, and you can build pacman artefacts somehow, at least that's what the docs say. Would that help?

**Comment by R8s6** [comment]
Hi @pascalopitz , when I run 
`npm run fonts`

I get this error:
```
> mkdir -p ./app/fonts && cp ./node_modules/material-design-icons/iconfont/* ./app/fonts/
cp: cannot stat './node_modules/material-design-icons/iconfont/*': No such file or directory
```
It appears that the "node_modules" directory is not included in the source code, if this is the case, could you please kindly include it? Thanks!
