### ISSUE TITLE
Low res screens

### ISSUE THREAD

**Issue by michiil** [pascalopitz/unoffical-sonos-controller-for-linux#7]
Im running your app on a Raspberry pi Touchscreen (800x480)
The UI works pretty well, apart from the queue. Would be nice if there would be an option to minimize the now playing view!

![unoffical sonos controller for linux_004](https://cloud.githubusercontent.com/assets/5451489/21073014/b3839dfa-bed4-11e6-859c-78d05c59eb73.png)

**Comment by pascalopitz** [comment]
See https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/issues/6#issuecomment-265943975

**Comment by pascalopitz** [comment]
Hi there. I am sure we can arrange that.

**Comment by pascalopitz** [comment]
Expand/Collapse available as of https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.0.9-alpha2

**Comment by pascalopitz** [comment]
@michiil can this be closed now?

**Comment by michiil** [comment]
Yep, just tried it, perfect!
Thank you!
