### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by t0m4s** [pascalopitz/unoffical-sonos-controller-for-linux#75]
Hi,

I've translated your app in French.
Patch available here : http://thomas.morlon.free.fr/unofficial-sonos_FR.diff
Usage :
- save patch file at the root of your unoffical-sonos-controller-for-linux project.
- run **patch -p1 < unofficial-sonos_FR.diff** in your console

The patch also replaces **searchType: 'A:ARTIST'** by **searchType: 'A:ALBUMARTIST'** in the library browser (BrowserListConstants.js). Seems more convenient to me.

Thanks for developing this app !!

See you.

**Comment by pascalopitz** [comment]
Hi, I don't think it's good to build multiple versions for each lang.
