### ISSUE TITLE
Allow searching over Music Services

### ISSUE THREAD

**Issue by mashtonian** [pascalopitz/unoffical-sonos-controller-for-linux#79]
It seems that one can currently only search the Music Library?

**Comment by pascalopitz** [comment]
You can search in each service, once you navigated to it. The search bar flicks to search in that particular service only.

![Peek 2020-06-02 08-06](https://user-images.githubusercontent.com/271740/83461511-1874f300-a4a8-11ea-89d9-24e88fba478c.gif)

**Comment by mashtonian** [comment]
Gotcha. Close this one.
