### ISSUE TITLE
Boost showing in Room list

### ISSUE THREAD

**Issue by stan-qaz** [pascalopitz/unoffical-sonos-controller-for-linux#82]
My Boost is also showing in Room list. I saw this mentioned on the Sonos forums and saw it on my Beta 5 so I'm sending in the state file requested there. Renamed by adding the .txt to upload.

[beta5-boost-unoffical-sonos-controller.appState.json.txt](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4741555/beta5-boost-unoffical-sonos-controller.appState.json.txt)

Sonos post: https://en.community.sonos.com/controllers-software-228995/sonos-on-ubuntu-linux-spotify-6837636#post16435722

**Comment by pascalopitz** [comment]
Try beta 6 which I've just pushed.

**Comment by stan-qaz** [comment]
That seems to have fixed it, no Boost on the Rooms menu now.
