### ISSUE TITLE
Equaliser Panel

### ISSUE THREAD

**Issue by pascalopitz** [pascalopitz/unoffical-sonos-controller-for-linux#84]
Equaliser panel feature:

https://en.community.sonos.com/controllers-software-228995/sonos-on-ubuntu-linux-spotify-6837636?postid=16436192#post16436192

**Comment by pascalopitz** [comment]
Still missing: L/R

**Comment by Avinguda21** [comment]
Thanks.  Works.
Another point - artwork is missing from Music Library ...

**Comment by Avinguda21** [comment]
Oops - I'm castalla from Sonos forum

**Comment by pascalopitz** [comment]
> Another point - artwork is missing from Music Library ...

That's not this ticket though. Can you make a new one and attach some screenshots etc?
