### ISSUE TITLE
Strange character in Music Library listing

### ISSUE THREAD

**Issue by Avinguda21** [pascalopitz/unoffical-sonos-controller-for-linux#85]
There's a 'ghost' entry with strange characters in my Music Library listing for Albums - see attached file

This image also shows the missing artwork problem

![beta8](https://user-images.githubusercontent.com/45179453/84567016-1f3c1980-ad76-11ea-8e2e-63bbc597f15f.png)

**Comment by pascalopitz** [comment]
So ... .m3u, that's a playlist? Can you attach a state dump file I can inspect?

**Comment by Avinguda21** [comment]
Yes - playlist in m3u format.  Fairly certain it's new ...


[state dump.txt](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4774880/state.dump.txt)

**Comment by pascalopitz** [comment]
Sorry, that's not the app state, but a console output log.

**Comment by Avinguda21** [comment]
app state
[unoffical-sonos-controller.appState.json.txt](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4778131/unoffical-sonos-controller.appState.json.txt)

**Comment by pascalopitz** [comment]
Well, that looks like the browse response on the indexed m3u contains the item, including the strange characters. I had a loom through my stuff, and even despite containing german language stuff with umlauts etc, it all seems to have been indexed without funky characters. Not sure what the sonos indexer has done there, but my app just consumes the response from the sonos players.

Out of interest, when you browse the same item in the native controller app, how does the playlist get displayed there?

**Comment by pascalopitz** [comment]
Ok. Found one, but on the controller shows the same. 
![Screenshot_20200615-171929](https://user-images.githubusercontent.com/271740/84631460-90bdc880-af2c-11ea-89b2-955730900fcf.png)

**Comment by pascalopitz** [comment]
Again, this is down to indexing the filesystem and something that has nothing to do with the controller app. Closing this for now.

**Comment by Avinguda21** [comment]
You're right.  Didn't see this in the older controller - something has changed somewhere.  Thanks anyhow.
