### ISSUE TITLE
Artwork missing in Music Library

### ISSUE THREAD

**Issue by Avinguda21** [pascalopitz/unoffical-sonos-controller-for-linux#86]
Artwork no longer shows in Music Library.
See previous issue for example.

**Comment by pascalopitz** [comment]
See #85?
Is the artwork not loading on all Music Library Items, or just playlists? Have you recently re-indexed it? What software version do the players run? S1 or S2?

**Comment by Avinguda21** [comment]
No artwork on any Library views.  Reindexed yesterday.  Using S1.

**Comment by Avinguda21** [comment]
Oops - closed by error

**Comment by pascalopitz** [comment]
I cannot replicate this. Anybody getting the same?

**Comment by My-Random-Thoughts** [comment]
My library view is fine as is my playlist and everywhere.
The "Now Playing" artwork is blank when I first open the app, but OK when the track changes.

**Comment by pascalopitz** [comment]
Ok, I think I'll close this. There is however a whole lot of optimisation that I want to do around artwork loading. But that's another story.
