### ISSUE TITLE
Deezer Flow just plays one song

### ISSUE THREAD

**Issue by FlorentChabaud** [pascalopitz/unoffical-sonos-controller-for-linux#87]
First, thanks for this unofficial Sonos controller. It already appears rock solid and even more stable in certain cases than the official ones I'm using on Android!

Just posting to let you know of a small problem in Deezer support. I know this is experimental, and it works pretty well already, but there is one tweak that could make my day.

Deezer proposes a "Personal Flow" channel. Never ending stream proposing music one after the other in a profiled way. I've tried two ways to use it from your controller, but both fails.

- When selecting it from your controller it plays the first song and then just stops. The song is added to the playlist.
- If the Flow has been added as a Sonos favorite, it is displayed but doesn't work at all.

I think the simplest way to fix this would be to identify this type of stream where you need to reload the next song at the end of the previous one.

**Comment by pascalopitz** [comment]
Interesting. Can you export the app state (see the developer menu) and upload it here for inspection?

**Comment by FlorentChabaud** [comment]
Sorry for the late answer. I had to find the time for that.
[unoffical-sonos-controller.appState.zip](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4850794/unoffical-sonos-controller.appState.zip)

**Comment by pascalopitz** [comment]
I can see it's itemType "program". I don't think the controller software does interact with it once it is scheduled correctly. I guess the scheduling part is the problem.

Could you do me a favour and schedule the program from another app where it works, i.e. Android and then give me a state dump when it's displaying as current track in one of the players? That might give us a clue as to what the other app has queued up?

**Comment by FlorentChabaud** [comment]
Sure. There you are. I have launched it both from Deezer & Sonos Favorites.

[unoffical-sonos-controller.appState.zip](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4851712/unoffical-sonos-controller.appState.zip)

**Comment by FlorentChabaud** [comment]
To note that nothing appears in the queue during playing from the Android controller. On the contrary, when started from Linux the queue is populated with the one-track which is added.

**Comment by pascalopitz** [comment]
I can see a custom protocol `x-sonosprog-http:tr%3a3113922.mp3?sid=2&flags=8224&sn=1` ... not sure how the mp3 url is constructed and if it's changing for every track in the program?

**Comment by FlorentChabaud** [comment]
Let me know if you need some testing on my side.
Indeed it seems that the main difference between the track started from Android and the one from Linux is on the protocol specified (sonosprog instead of sonos):

```
"albumArtURI": "http://192.168.1.100:1400/getaa?s=1&u=x-sonosprog-http%3atr%253a3113922.mp3%3fsid%3d2%26flags%3d8224%26sn%3d1",
"uri": "x-sonosprog-http:tr%3a3113922.mp3?sid=2&flags=8224&sn=1",


``````

**Comment by pascalopitz** [comment]
So how do you kick this off? You pick a track to play or a playlist?

**Comment by FlorentChabaud** [comment]
More like a radio I'd say. I've added in the archive a second snapshot. I haven't interrupted the flow so that you can have a look at the history.

[unoffical-sonos-controller.appState.zip](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4852198/unoffical-sonos-controller.appState.zip)

**Comment by FlorentChabaud** [comment]
It appears on top of the service.
![image](https://user-images.githubusercontent.com/34078058/86133730-0018e800-bae9-11ea-8b0c-3ca94a717d08.png)

**Comment by FlorentChabaud** [comment]
And in Favorites it is listed together with a preset radio.
![image](https://user-images.githubusercontent.com/34078058/86134054-6ef64100-bae9-11ea-8e3b-33436922eac5.png)

**Comment by pascalopitz** [comment]
Yes. So the problem I have there is this: The item has the id flow and itemType program. However, the urls that come through are the tracks inside that program's playlist. I am not quite sure how to construct a correct URL for the player to make that work. Will have to investigate. Unfortunately Deezer is a paid subscription, and I don't want to throw money at the problem really.

**Comment by FlorentChabaud** [comment]
The Deezer free subscription should let you use the Flow. If I remember well, the Free subscription doesn't let you select a track. You can just use the Flow. But this may be sufficient for tracking this issue. Otherwise, I can give a try to any patch if you want me to test something (and I find the time for it).

**Comment by pascalopitz** [comment]
What I would do normally is MIM an android device and sniff the UPNP
payload to the player. I'll see if I can sign up for free and make that
work.

**Comment by FlorentChabaud** [comment]
Sorry I need to drop but is it what you are looking for?
![image](https://user-images.githubusercontent.com/34078058/86142275-4d01bc00-baf3-11ea-996b-d24bc78a797d.png)

**Comment by pascalopitz** [comment]
No free trial in Australia :(

![image](https://user-images.githubusercontent.com/271740/86186390-1e79f480-bb78-11ea-8d21-4f432a6c96e1.png)

**Comment by pascalopitz** [comment]
@FlorentChabaud Wireshark might work. You're looking for a UPNP call to `/MediaRenderer/AVTransport/Control` with a header `SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"`.

**Comment by FlorentChabaud** [comment]
```
eXtensible Markup Language
    <s:Envelope
        xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
        s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
            <u:SetAVTransportURI
                xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
                <InstanceID>
                    0
                    </InstanceID>
                <CurrentURI>
                    x-sonosapi-radio:flow?sid=2&amp;flags=8296&amp;sn=1
                    </CurrentURI>
                <CurrentURIMetaData>
                     [truncated]&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-o
                    </CurrentURIMetaData>
                </u:SetAVTransportURI>
            </s:Body>
        </s:Envelope>

And here is the complete metadata:

`&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;100c2068flow&quot; parentID=&quot;0&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Flow, your personal mix&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.audioBroadcast.#DEFAULT&lt;/upnp:class&gt;&lt;upnp:albumArtURI&gt;https://cdns-files.dzcdn.net/cache/images/partners/sonos/flow_legacy.c0d705f2d93293606ef66ce7ca252b9c.png&lt;/upnp:albumArtURI&gt;&lt;r:description&gt;Deezer&lt;/r:description&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON519_X_#Svc519-8e734d36-Token&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;`

Let me know if this is what you are looking for.

**Comment by FlorentChabaud** [comment]
The same from Linux:

```
eXtensible Markup Language
    <s:Envelope
        xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
        s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
            <u:AddURIToQueue
                xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
                <InstanceID>
                    0
                    </InstanceID>
                <EnqueuedURI>
                    x-rincon-cpcontainer:000c206cflow
                    </EnqueuedURI>
                <EnqueuedURIMetaData>
                     [truncated]&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;\n        xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;\n        xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;\n        xml
                    </EnqueuedURIMetaData>
                <DesiredFirstTrackNumberEnqueued>
                    0
                    </DesiredFirstTrackNumberEnqueued>
                <EnqueueAsNext>
                    1
                    </EnqueueAsNext>
                </u:AddURIToQueue>
            </s:Body>
        </s:Envelope>
```
With the complete value:
```
&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;
        xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;
        xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;
        &lt;item id=&quot;000c206cflow&quot; restricted=&quot;true&quot; &gt;
        &lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON519_&lt;/desc&gt;
        &lt;dc:title&gt;Flow, your personal mix&lt;/dc:title&gt;
        &lt;upnp:class&gt;object.item.audioItem.audioBroadcast.#DEFAULT&lt;/upnp:class&gt;
        
        &lt;/item&gt;
        &lt;/DIDL-Lite&gt;`
```

**Comment by FlorentChabaud** [comment]
I believe the main difference is on the method used instead of <EnqueuedURI> it's <CurrentURI> with radio API:
```
<CurrentURI>
                    x-sonosapi-radio:flow?sid=2&amp;flags=8296&amp;sn=1
</CurrentURI>                
```

**Comment by FlorentChabaud** [comment]
BTW, I have tested all the other Deezer features, and everything works really well, including search bar, and icon downloading. Impressive, bravo!
![image](https://user-images.githubusercontent.com/34078058/86254543-3ff9d100-bbb6-11ea-9e80-00977971c83f.png)

**Comment by pascalopitz** [comment]
Super helpful. awesome.

**Comment by pascalopitz** [comment]
How comfortable are you running the code straight off a branch? https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/tree/deezer-radio-fix

**Comment by FlorentChabaud** [comment]
Not very familiar with node.js but I was able to compile & run the development app from a zip, after a couple of upgrades on my ubuntu.
Unfortunately it doesn't work. There is even a slight regression: clicking on the flow just displays the first track but no more start it.

**Comment by FlorentChabaud** [comment]
Yet, I just noticed something interesting: the next track is present in the display even if it is not started at the end of the song.

![image](https://user-images.githubusercontent.com/34078058/86330900-9fa0bc80-bc48-11ea-91cb-4f7c57b22dd5.png)

**Comment by FlorentChabaud** [comment]
Discovering the console:
![image](https://user-images.githubusercontent.com/34078058/86336444-27d69000-bc50-11ea-8d10-a5ffdd5aa77a.png)

**Comment by pascalopitz** [comment]
I did a slight tweak. Can you pull and give it another try?
There is a service token in your payload which I cannot fully reconstruct. `SA_RINCON519_X_#Svc519-8e734d36-Token` . However, I think for all other interactions we're constructing `SA_RINCON519_X_#Svc519-0-Token`, and they work? Where the `8e734d36` id comes from is beyond me, but I hope it doesn't matter in the end.

**Comment by FlorentChabaud** [comment]
Hold on... Give it a try

**Comment by FlorentChabaud** [comment]
OK. We progress. I was able to launch the Flow without above error. But clicking on Next gives the same error.
![image](https://user-images.githubusercontent.com/34078058/86339541-0081c200-bc54-11ea-8d0d-9b8bb15ee7f2.png)
Now waiting for the end of the first song to see what happens.

**Comment by FlorentChabaud** [comment]
OK, no change in the end. The track stops and nothing.
![image](https://user-images.githubusercontent.com/34078058/86339836-58b8c400-bc54-11ea-8828-5a1ef08d3e15.png)

**Comment by pascalopitz** [comment]
So, hang on. You can now schedule the first song okay but it fails on the next song?
The next song isn't scheduled by my software, but the sonos player itself. Can we compare the payloads of the `SetAVTransportURI` calls?

**Comment by pascalopitz** [comment]
This is pretty hard without having a deezer subscription :/

**Comment by FlorentChabaud** [comment]
And with 12h difference ;-)

**Comment by FlorentChabaud** [comment]
OK. I'll try to capture the payload with the current version.

**Comment by FlorentChabaud** [comment]
```
&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;
        xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;
        xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;
        &lt;item id=&quot;000c206cflow&quot; restricted=&quot;true&quot; &gt;
        &lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON519_&lt;/desc&gt;
        &lt;dc:title&gt;Flow, your personal mix&lt;/dc:title&gt;
        &lt;upnp:class&gt;object.item.audioItem.audioBroadcast.#DEFAULT&lt;/upnp:class&gt;
        
        &lt;/item&gt;
        &lt;/DIDL-Lite&gt;
```

**Comment by FlorentChabaud** [comment]
![image](https://user-images.githubusercontent.com/34078058/86342688-3f197b80-bc58-11ea-837f-6f162d36bac1.png)

**Comment by FlorentChabaud** [comment]
Also noted in console:
![image](https://user-images.githubusercontent.com/34078058/86342982-a0d9e580-bc58-11ea-9688-ee931dd091ec.png)

**Comment by pascalopitz** [comment]
Sorry, which revision are you on?

**Comment by FlorentChabaud** [comment]
I've pulled the git from your deezer branch

**Comment by FlorentChabaud** [comment]
Hold on... I'm checking

**Comment by FlorentChabaud** [comment]
My fault. I forgot to use the branch tag when pulling. Where can I double check the version in the interface?

**Comment by FlorentChabaud** [comment]
So I wasn't able to launch with the deezer branch.
![image](https://user-images.githubusercontent.com/34078058/86344952-370f0b00-bc5b-11ea-935f-aae67e11aa00.png)
I'll go and capture the payload

**Comment by FlorentChabaud** [comment]
![image](https://user-images.githubusercontent.com/34078058/86345105-66be1300-bc5b-11ea-909f-7f8a5acf9fe7.png)

**Comment by FlorentChabaud** [comment]
```
&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;
        xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;
        xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;
        &lt;item id=&quot;100c2068flow&quot; restricted=&quot;true&quot; parentID=&quot;0&quot;&gt;
        &lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON519_X_#Svc519-0-Token&lt;/desc&gt;
        &lt;dc:title&gt;Flow, your personal mix&lt;/dc:title&gt;
        &lt;upnp:class&gt;object.item.audioItem.audioBroadcast.#DEFAULT&lt;/upnp:class&gt;
        
        &lt;/item&gt;
        &lt;/DIDL-Lite&gt;
```

**Comment by pascalopitz** [comment]
Ok, I just paid 11 dollars for a month of Deezer :/
Fixed. will push out new beta revision.

**Comment by pascalopitz** [comment]
So, to wrap this up, there were a couple of things at play here:

- The URI:  x-sonosapi-radio:flow?sid=2&amp;flags=8296&amp;sn=1
- The metadata ID: 100c2068flow
- The service ID: SA_RINCON519_X_#Svc519-0-Token
- The fact that the app tried to add it to the queue, even though it was a non queueable item

I also made sure that items that have `canEnumerate='false'` are non browsable and an item of type "program" can only be used with "Play Now", like other broadcast items.

**Comment by FlorentChabaud** [comment]
I confirm it works. One slight difference which remains is that the next button is not available contrary to the native controller.
Thanks for this!

**Comment by FlorentChabaud** [comment]
I didn't want to let you without a contribution ;-)

[Deezer-next-button.patch.txt](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/files/4865707/Deezer-next-button.patch.txt)

Sorry if the code is a little childish, that's my first one in node.js but this way one can push the next button. I have tried to push on the github branch but I guess I haven't the right to do so.

**Comment by pascalopitz** [comment]
Yes, pushing directly against other people's branches doesn't work. The way to do this would be to create your own fork in github, commit your changes there, then create a pull request which I can merge in.

But this is awesome. Thanks for the contribution. I'll merge the patch.

**Comment by FlorentChabaud** [comment]
Thanks. I'll run through this for my next contribution if any. Thanks again.
