### ISSUE TITLE
Is SONOS v2 supported?

### ISSUE THREAD

**Issue by guffedk** [pascalopitz/unoffical-sonos-controller-for-linux#88]
Does anybody know if SONOS v2 is supported by this? This is in no way a complaint - just asking...

**Comment by pascalopitz** [comment]
I won't upgrade, so I don't really know?

**Comment by juh** [comment]
I've upgraded my Sonos system and version 0.1.6 still works here.

**Comment by pascalopitz** [comment]
@juh Have you tried the latest v0.2.0-beta?

**Comment by FlorentChabaud** [comment]
Using 0.2.0-beta11 and works fine with Sonos-v2

**Comment by juh** [comment]
> @juh Have you tried the latest v0.2.0-beta?
No, not yet, but as @FlorentChabaud reported, it seems to work. Will upgrade now :-)

**Comment by svrooij** [comment]
For my Sonos library (which uses a generator to discover all possible Sonos commands) we have tested the V2 system and it generated the same services. So from that point of view, if it has all the same services, all apps working against V1 will also work against V2.

https://github.com/svrooij/node-sonos-ts/issues/64

**Comment by pascalopitz** [comment]
Sounds like yes then!
