### ISSUE TITLE
slacker

### ISSUE THREAD

**Issue by xxcriticxx** [pascalopitz/unoffical-sonos-controller-for-linux#9]
@pascalopitz you can add and open pick your song but song wont play

![screenshot from 2016-12-16 21-45-05](https://cloud.githubusercontent.com/assets/15007183/21283854/60bad070-c3d9-11e6-81c7-60b87f44262e.png)

**Comment by pascalopitz** [comment]
See https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/issues/6#issuecomment-265943975

**Comment by xxcriticxx** [comment]
@pascalopitz i know what you said i just tested and post my findings

**Comment by pascalopitz** [comment]
Can we try this in alpha6 pre-release? A lot has changed since then.

**Comment by xxcriticxx** [comment]
alpha5 service is very slow. search works. artwork dont work small problem. found songs but could not get it to play the song.

**Comment by pascalopitz** [comment]
Again, no slacker in Australia. Cannot test why it doesn't play.

**Comment by xxcriticxx** [comment]
no problem i use from time to time only i live without it
