### ISSUE TITLE
Sonos 2.0

### ISSUE THREAD

**Issue by MaxJonasG** [pascalopitz/unoffical-sonos-controller-for-linux#91]
Thank you for keeping this alive. All working for me as expected. This is not an issue but I couldn’t find a contact formula. Am I right in believing that we shouldn’t update to Sonos 2.0 if we want to continue to use your controller? The app keeps pestering me on my phone.

**Comment by pascalopitz** [comment]
Glad you like it. Sonos v2 has been discussed here:

https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/issues/88
