### ISSUE TITLE
Use Sonos Beam as audio output in Ubuntu

### ISSUE THREAD

**Issue by Benzer1406** [pascalopitz/unoffical-sonos-controller-for-linux#95]
Hi,
I just wanted to leave the question if it's possible to have the Sonos Beam as audio output in the Linux settings such that system sounds and sounds from website, e.g. YouTube are reproduced.

Thanks

**Comment by pascalopitz** [comment]
Is that something that works on native client apps? As with the soundbar
and TV input, I don't have a BEAM, so no means to test this.

**Comment by pascalopitz** [comment]
Out of scope for this project.
I think you might be able to target Sonos devices directly as DLNA outputs, but I have never tried it.

https://askubuntu.com/questions/187086/how-do-i-set-up-live-audio-streams-to-a-dlna-compliant-device

**Comment by Benzer1406** [comment]
@pascalopitz  On macOS it is a standard feature. I just select as sound output the Sonos speaker and all audio is routed to the speaker.
