### ISSUE TITLE
RPM build target

### ISSUE THREAD

**Issue by pascalopitz** [pascalopitz/unoffical-sonos-controller-for-linux#98]
>Hi Pascal,
>
>My name is W and I have a question for you. I'm using OpenSuse Tumbleweed. This is an RPM base linux and I was wondering if you could make a version for Suse (RPM) also? I tried alien to convert the deb to rpm but this fails.
>
>Regards,
>
>W

**Comment by wjterveld** [comment]
Hi Pascal,

The appimage is working fine!!! only it will not find my Sonos system? I keeps searching for it.

**Comment by pascalopitz** [comment]
Make sure you have the relevant ports open.

https://github.com/pascalopitz/unoffical-sonos-controller-for-linux#firewall-settings

**Comment by pascalopitz** [comment]
RPMs now part of the release build:

https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.2.1-alpha6
